### ISSUE TITLE
total_including_tax - Call to a member function raw() on int

### ISSUE THREAD

**Issue by de-raaf-media** [damcclean/simple-commerce#1035]
### Description

In version 5 an object is passed. For some reason in version 6 an integer is passed.

**Version 5 - entries table**

_This seems to be the correct way. An object is passed._

```
{
	"items": [
		{
			"id": "0b048878-f46f-434d-8341-27c8fb822d1d",
			"tax": {
				"rate": 21,
				"amount": 174,
				"price_includes_tax": true
			},
			"total": 826,
			"product": "00c83cb1-6089-4785-9479-b5032c6f1bc3",
			"variant": {
				"product": "00c83cb1-6089-4785-9479-b5032c6f1bc3",
				"variant": "default"
			},
			"metadata": [],
			"quantity": 1
		}
	],
	
}
```

**Result:**

```
Statamic\Fields\Value {#3460 ▼ // vendor/doublethreedigital/simple-commerce/src/Tags/TotalIncludingTax.php:13
  #raw: 826
  #handle: "total"
  #fieldtype: DoubleThreeDigital\SimpleCommerce\Fieldtypes\MoneyFieldtype {#3476 ▶}
  #augmentable: Statamic\Eloquent\Entries\Entry {[#2110 ▶](https://webshop2.tuindingen.test/cart#sf-dump-617803364-ref22110)}
  #shallow: false
}
```

**Version 6 - Orders table**

_This seems incorrect. An integer is passed as total._

	{
		"id": "70b0279c-3bee-4b62-827f-39cd1f72fe90",
		"tax": {
			"rate": 21,
			"amount": 174,
			"price_includes_tax": true
		},
		"total": 826,
		"product": "4d0c8f81-4ea4-4b03-b864-d1e6317440da",
		"variant": {
			"product": "4d0c8f81-4ea4-4b03-b864-d1e6317440da",
			"variant": "default"
		},
		"metadata": [],
		"quantity": 1
	}

**Result:**

826 // vendor/doublethreedigital/simple-commerce/src/Tags/TotalIncludingTax.php:13

Output without {{ total_including_tax }}

**If I leave out total_including_tax from antlers I get the following results.** 

**for version 5**

    sc:cart:total - €15.00 - Returns the overall/grand total of the cart
    sc:cart:grand_total - €15.00 - Does the same thing as sc:cart:total
    sc:cart:items_total - €8.26 - Returns the total of all line items.
    sc:cart:shipping_total - €5.00 - Returns the shipping total of the cart.
    sc:cart:shipping_total_with_tax - €5.00 - Return the shipping total, inclusive of any tax.
    sc:cart:tax_total - €1.74 - Returns the tax total of the cart.
    sc:cart:tax_total_split - - Returns the tax total of the cart, split by tax rate.
    sc:cart:coupon_total - €0.00 - Returns the total amount saved from coupons.
    sc:cart:items_total_with_tax - €10.00 - Returns the total of all line items, inclusive of any tax.

**for version 6**

    sc:cart:total - 1000 - Returns the overall/grand total of the cart
    sc:cart:grand_total - 1000 - Does the same thing as sc:cart:total
    sc:cart:items_total - 826 - Returns the total of all line items.
    sc:cart:shipping_total - 0 - Returns the shipping total of the cart.
    sc:cart:shipping_total_with_tax - €0.00 - Return the shipping total, inclusive of any tax.
    sc:cart:tax_total - 174 - Returns the tax total of the cart.
    sc:cart:tax_total_split - - Returns the tax total of the cart, split by tax rate.
    sc:cart:coupon_total - 0 - Returns the total amount saved from coupons.
    sc:cart:items_total_with_tax - €10.00 - Returns the total of all line items, inclusive of any tax.

### Steps to reproduce

I created a separate branch to upgrade to version 6. There I switched orders from eloquent to database orders. 

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.48.4
PHP Version: 8.2.16
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: domain6.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 3
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 PRO

Statamic Addons
doublethreedigital/simple-commerce: 6.0.10
statamic-rad-pack/runway: 6.6.1
statamic/eloquent-driver: 3.3.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file

**Comment by duncanmcclean** [comment]
> There I switched orders from eloquent to database orders.

I think this may be part of the reason you're running into this issue, since none of the totals you're showing for v6 are being augmented like they should be.

What does your `resources/blueprints/vendor/runway/order.yaml` file look like?

**Comment by de-raaf-media** [comment]
This looks a bit empty. Did I miss a step?

```
tabs:
  main:
    fields: {  }

```

**Comment by duncanmcclean** [comment]
Can you try copying the contents of this file into there and let me know if it helps?

https://github.com/duncanmcclean/simple-commerce/blob/6.x/src/Console/Commands/stubs/runway_order_blueprint.yaml

It should be copying it over as part of the "move to database" process but something must have went weird.

**Comment by de-raaf-media** [comment]
"**Unsupported operand types: int + string**"

seems to be hanging on map in this function:


```
public function rawTaxTotalSplit(): Collection

    {

        return collect($this->items())

            ->groupBy(function ($item) {

                return $item['tax']['rate'];

            })

            ->map(function ($group, $groupRate) {

                return [

                    'rate' => $groupRate,

                    'amount' => $group->sum(function ($item) {

                        return $item['tax']['amount'];

                    }),

                ];

            })

            ->values();

    }
```

**Comment by duncanmcclean** [comment]
Hmm, looks like something that should be a number isn't a number. Can you share the contents of the `items` column for your current order?

**Comment by de-raaf-media** [comment]
Sure, here you go:

```
[
	{
		"id": "18fb0585-3e23-45f1-abd9-a0b6848f17ba",
		"tax": {
			"rate": 21,
			"amount": 260,
			"price_includes_tax": true
		},
		"total": 1240,
		"product": "00c83cb1-6089-4785-9479-b5032c6f1bc3",
		"variant": {
			"product": "00c83cb1-6089-4785-9479-b5032c6f1bc3",
			"variant": "default"
		},
		"metadata": [],
		"quantity": 1
	}
]
```

**Comment by duncanmcclean** [comment]
That looks okay to me 🤔 

> "Unsupported operand types: int + string"

Are you able to provide the full stack trace for this error?

**Comment by de-raaf-media** [comment]
I just added a dd in RawTaxTotalSplit:

`dd($item['tax']['amount']);`

result: €2.60

If I convert the amount to int it works:

`return intval($item['tax']['amount']);`

The cart now shows correctly.

sc:cart:total - €25.00 - Returns the overall/grand total of the cart
sc:cart:grand_total - €25.00 - Does the same thing as sc:cart:total
sc:cart:items_total - €20.66 - Returns the total of all line items.
sc:cart:shipping_total - €0.00 - Returns the shipping total of the cart.
sc:cart:shipping_total_with_tax - €0.00 - Return the shipping total, inclusive of any tax.
sc:cart:tax_total - €4.34 - Returns the tax total of the cart.
sc:cart:tax_total_split - - Returns the tax total of the cart, split by tax rate.
sc:cart:coupon_total - €0.00 - Returns the total amount saved from coupons.
sc:cart:items_total_with_tax - €25.00 - Returns the total of all line items, inclusive of any tax.

**Comment by de-raaf-media** [comment]
`return intval($item['tax']['amount'])` seems to do the trick. Do you need more info from me?

**Comment by duncanmcclean** [comment]
`$item['tax']['amount']` should already be an integer (it is in the [data you provided](https://github.com/duncanmcclean/simple-commerce/issues/1035#issuecomment-2018336591)).

I just need to find some time to dig into it a bit more, I don't need anything from you. :)

**Comment by de-raaf-media** [comment]
Maybe this helps?

```
'amount' => $group->sum(function ($item) {
    dd($item['tax']);
```
Result:
```
array:3 [▼ // vendor/doublethreedigital/simple-commerce/src/Tags/CartTags.php:174
  "rate" => 21
  "amount" => "€1.74"
  "price_includes_tax" => true
]

**Comment by duncanmcclean** [comment]
From a very brief look, I _think_ it's happening because `$this->items()` returns the augmented line items:

https://github.com/duncanmcclean/simple-commerce/blob/a988310fe89af13e0ba923dd700fee598487bbe2/src/Tags/CartTags.php#L163

It should probably be using the "raw" line item data from the order instead. I'll try and take a look at this issue this week. For now, you could maybe use a [composer patch](https://rias.be/blog/using-composer-patches) if you need it fixed for now.

**Comment by de-raaf-media** [comment]
Cool. Didn't know about "composer patch".

**Comment by duncanmcclean** [comment]
Just tagged a release ([v6.0.11](https://github.com/duncanmcclean/simple-commerce/releases/tag/v6.0.10)) which should fix it.
