### ISSUE TITLE
Undefined method error in UserCustomerRepository

### ISSUE THREAD

**Issue by jacksleight** [damcclean/simple-commerce#1078]
### Description

When submitting the checkout details form we're getting this error:

```
Call to undefined method Statamic\Auth\Eloquent\User::merge()
DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository : 102
```

When storing customers as users.

### Steps to reproduce

Store customers as users, try to submit the checkout details form.

### Environment

SC 7.2.0

**Comment by duncanmcclean** [comment]
It seems like Statamic's Eloquent `User` class is missing the `->merge()` method which exists on the file users implementation.

I've opened a PR on the Statamic side to add it: statamic/cms#10192

**Comment by duncanmcclean** [comment]
PR has been merged, will be fixed in the next version of Statamic.
