### ISSUE TITLE
Adding a second asset container breaks my shop.

### ISSUE THREAD

**Issue by sbrow** [damcclean/simple-commerce#1112]
### Description

I recently added a new asset container to my application, to host our videos on Amazon  S3.

At first, I assumed this error was my bad (and it might still be), however, the stack trace might indicate otherwise:
![Screenshot_20240727_150537](https://github.com/user-attachments/assets/5b14b9ad-305b-4eff-822c-93e97704801c)

### Steps to reproduce

Start with a basic setup that has only one asset container.

1. Setup a shop and add some products
2. Add images to those products
3. After verifying that everything works as intended, add a new asset container.
4. Visit the shop page or try to edit a product - you should encounter the error.

### Environment

Environment
Application Name: &lt;REDACTED>
Laravel Version: 11.7.0
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: &lt;REDACTED>.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: USD
Gateways: Stripe
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Flat Rate Shipping, Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.5.1
PHP SDK Version: 4.7.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: 100%
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 8
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.2 PRO

Statamic Addons
arthurperton/wordpress-users: 1.2.0
duncanmcclean/guest-entries: 4.0.1
duncanmcclean/simple-commerce: 7.3.0
&lt;REDACTED>/sc-affiliates: dev-e6933fba7b6eebf38cb98e5cf1aab5a4c8fe6f8e
&lt;REDACTED>/sc-checkout: dev-e6933fba7b6eebf38cb98e5cf1aab5a4c8fe6f8e
&lt;REDACTED>/sc-subscriptions: dev-e6933fba7b6eebf38cb98e5cf1aab5a4c8fe6f8e
sbrow/banner: dev-e6933fba7b6eebf38cb98e5cf1aab5a4c8fe6f8e
statamic/seo-pro: 6.0.3

**Comment by duncanmcclean** [comment]
You can fix this by specifying an asset container on the Asset field you have as a product variant option.

**Comment by duncanmcclean** [comment]
Have you added any custom fields to the Product Variants field in the blueprint?

**Comment by sbrow** [comment]
Thanks! My issue turned out to be that although I set a container for Photos in the `Product` and `Variable Product` Blueprints, I forgot to set it for "Downloadable Asset". Now everything works, I think.

Hopefully this will help anyone else whom may have this issue :)
