### ISSUE TITLE
Default tax rate not applied using StandardTaxEngine

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#1116]
### Description

When adding the first product to the order without knowning the country yet, it should use the default address tax rate. However when I debug the code it thinks that there is an Address, while the Address is all 'null': 

```php
    protected function decideOnLineItemRate(Order $order, LineItem $lineItem): ?StandardTaxRate
    {
        $product = $lineItem->product();

        /** @var \DuncanMcClean\SimpleCommerce\Orders\Address */
        $address = config('simple-commerce.tax_engine_config.address') === 'billing'
            ? $order->billingAddress()
            : $order->shippingAddress();

        dd($address->toArray()); // added this to check the content of $address

        if (! $address) {

            $noAddressProvided = config('simple-commerce.tax_engine_config.behaviour.no_address_provided');

            if ($noAddressProvided === 'default_address') {
                $address = $this->defaultAddress();
            }

            if ($noAddressProvided === 'prevent_checkout') {
                throw new PreventCheckout(__('This order cannot be completed as no address has been added to this order.'));
            }
        }
```
Debug statement returns: 
<img width="627" alt="image" src="https://github.com/user-attachments/assets/9fa6b0bb-c4a2-4787-bf8c-c1ea379ada66">

Due to this everything inside  `if (! $address)` is not executed, resulting in a random default TaxRate. 

In the end it is picking the 'Estonia (20%)' rate in our case as default now. 
```php
        return $taxRateQuery
            ->filter(function ($taxRate) use ($taxZoneQuery) {
                return $taxRate->zone()->id() === $taxZoneQuery->first()->id();
            })
            ->first();
```
<img width="374" alt="image" src="https://github.com/user-attachments/assets/88cdb6fa-e53d-495b-a8f9-9b53ca22acb0">

Can probably be solved by checking if the country / region of the Address is not empty? 
```php
private function isAddressEffectivelyEmpty(Address $address): bool
{
    return empty($address->region()) && empty($address->country());
}
```

The tax config looks like this: 
```
        'behaviour' => [
            'no_address_provided' => 'default_address',
            'no_rate_available' => 'default_rate',
        ],

        'default_address' => [
            ...
            'country' => 'NL',
            ...
        ],
```

### Steps to reproduce

1. Add product on a new order (using database)
2. Random tax rate is used as default tax rate 

### Environment

Application Name: XXX
Laravel Version: 11.18.1
PHP Version: 8.3.7
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: shipping_methods.collect.title, shipping_methods.sendcloud.title, shipping_methods.brenger.title, shipping_methods.mtc.title, shipping_methods.quicargo.title
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.17.0 PRO

Statamic Addons
aerni/advanced-seo: 2.8.0
aerni/font-awesome: 2.1.1
duncanmcclean/simple-commerce: 7.4.0
statamic-rad-pack/runway: 7.7.2

**Comment by duncanmcclean** [comment]
Hmm, the `Order::shippingAddress()` and `Order::billingAddress()` methods shouldn't be returning an empty address in the first place. 🤔

**Comment by Web10-Joris** [comment]
Thanks for fixing this Duncan 👍 I was surprised that no one else had yet encountered this problem
