### ISSUE TITLE
When Runway config is already present, database switch doesn't work as expected

### ISSUE THREAD

**Issue by Glenf** [damcclean/simple-commerce#1126]
### Description

When Runway config file is already present Simple Commerce resources won't be added to there.  This is because `publishRunwayConfig` checks only the existence of config file. (https://github.com/duncanmcclean/simple-commerce/blob/cfea47131e1596431ce7d61e5eef0cea0662102b/src/Console/Commands/SwitchToDatabase.php#L91)

This causes errors in CP, since the resources cannot be found.

Fix is to add these resources manually to Runway config from stubs (https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Console/Commands/stubs/runway_config.php)

Not sure what would be the best way to go forward with this one. Perhaps a cli notification to verify config file contents if config is already present. Better approach would be to check automatically if resources are present in the file and do the changes if needed. 

### Steps to reproduce

1. Create new Statamic project with database
2. Install Runway and it's config
3. Install Simple Commerce
4. Convert Simple Commerce to use database

### Environment

-

**Comment by duncanmcclean** [comment]
It should probably warn you it was unable to publish the Runway config file and that you should manually copy Simple Commerce's Runway config into your project.

I'd accept a PR.

**Comment by Glenf** [comment]
I can work on this later this month, if there's no hurry on this.
