### ISSUE TITLE
Gateway data Mollie stored on different places - Causing OrderNotFound exeception

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#1136]
### Description

Hi Duncan,
I finally managed to launch the webshop I was building the past months. Now we are experiencing some weird behaviour regarding the Mollie Gateway (and database orders?). 

I noticed some errors related to failing Mollie webhook calls that raised an _'Order related to Mollie transaction [tr_XXXXX] could not be found'_ exeception.

When looking into the database orders I saw that some orders do have Mollie data inside the `data` column, while others only have this (and even more data) on the `gateway` column. Out of the 48 orders, 13 orders have this piece stored in the `data` column:
```json
"mollie": {
  "id": "tr_[REDACTED]",
  "checkout_url": "https://www.mollie.com/checkout/select-method/[REDACTED]"
},
```

While the others have `"mollie": null` stored in the `data` column, therefore the webhook causing to fail in finding the correct order (for example when it is refunded from Mollie's dashboard). 

https://github.com/duncanmcclean/simple-commerce/blob/cfea47131e1596431ce7d61e5eef0cea0662102b/src/Gateways/Builtin/MollieGateway.php#L159

When checking out on the frontend everything is working as expected and the order is set to Paid. 

I can not find a pattern or specific condition on when this happens and for what orders, it looks completely random to me. 

If needed I can share a small database dump, then I have to redact all the PII, so let me know if needed. 

### Steps to reproduce

1. Enable database orders
2. Orders are coming and are paid using live Mollie API 

### Environment

Environment
Application Name: [REDACTED]
Laravel Version: 11.19.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: production
Debug Mode: OFF
URL: [REDACTED]/
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: redis
Database: mysql
Logs: daily
Mail: smtp
Queue: redis
Session: file

Simple Commerce
Currencies: EUR, EUR, EUR
Gateways: Mollie
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Pickup, DHL, Courier, Pallet Transport
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 5
Sites: 3 (Dutch, English, German)
Stache Watcher: Disabled
Static Caching: half
Version: 5.19.0 PRO

Statamic Addons
aerni/advanced-seo: 2.8.0
aerni/font-awesome: 2.1.1
duncanmcclean/simple-commerce: 7.4.1
statamic-rad-pack/meilisearch: 3.3.0
statamic-rad-pack/runway: 7.7.3

**Comment by duncanmcclean** [comment]
The `mollie` key should only be present in the order data [until the checkout process has been completed](https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Listeners/TidyTemporaryGatewayData.php).

The "permanent" information should be held under the `gateway` key - it'll store [pretty much the entire API response](https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Gateways/Builtin/MollieGateway.php#L99) we get back from Mollie.

Are you able to tell which orders are experiencing the issue and whether they're actually being marked as paid or not? It's possible we just need to [adapt this query](https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Gateways/Builtin/MollieGateway.php#L159) to also check the payment ID under the `gateway` key as well.

**Comment by Web10-Joris** [comment]
> The mollie key should only be present in the order data [until the checkout process has been completed](https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Listeners/TidyTemporaryGatewayData.php).
> The "permanent" information should be held under the gateway key - it'll store [pretty much the entire API response](https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Gateways/Builtin/MollieGateway.php#L99) we get back from Mollie.

Hmm in that case it is indeed better to check also the payment ID under the `gateway` key, as an order can be refunded from Mollie (causing webhook to fire). When the order was Paid (always in case of a refund via Mollie) it is not able to find it anymore in the current query. 

> Are you able to tell which orders are experiencing the issue and whether they're actually being marked as paid or not? 

The weird thing is that the orders are all marked as Paid. So 48 orders are marked as paid, where 13 orders still contain the `mollie` key in the order `data`.

**Comment by duncanmcclean** [comment]
I don't have a Mollie / Database Order site to easily test with. Would you be able to paste this snippet into `php artisan tinker` and let me know if it returns any results?

You'll obviously need to replace the ID with one which has been marked as paid and has data under the `gateway` key.

```php
\DuncanMcClean\SimpleCommerce\Facades\Order::query()->where('gateway->id', 'an-id-of-one-of-your-mollie-payments')->get();
```

**Comment by Web10-Joris** [comment]
I tried some debugging to get the order, it only worked with a `like` condition. I can access the id directly but not using the query.


<img width="991" alt="Scherm­afbeelding 2024-08-20 om 21 59 08" src="https://github.com/user-attachments/assets/ad0ec840-6711-4661-9ffb-b07db8e79f7f">


Edit: Oh and in your snippet you were still referencing `DoubleThreeDigital` instead of `DuncanMcClean` ;)

**Comment by duncanmcclean** [comment]
Thanks for digging into it.

What about if you try `data->gateway->id`? Does that work at all?

Hah, I noticed the wrong namespace a while after I posted it and updated my previous comment in case you hadn't seen it yet 😆

**Comment by Web10-Joris** [comment]
Unfortunately not
```
> DuncanMcClean\SimpleCommerce\Facades\Order::query()->where('data->gateway->id', 'tr_XXXXXX')->first()
= null
```

**Comment by duncanmcclean** [comment]
Okay, thanks for checking! The `like` condition should be fine for now. 👍

**Comment by duncanmcclean** [comment]
I've opened a PR (#1138) which should hopefully fix the issue. I'll get it merged & tagged tomorrow.

**Comment by Web10-Joris** [comment]
No problem, thanks for (hopefully) fixing it haha! Still don't know why some orders keep the `mollie` key inside `data` then, but that is not a big issue if the order lookup works again :)

**Comment by duncanmcclean** [comment]
We don't specifically remove the key from the order data, we just [set it to `null`](https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Listeners/TidyTemporaryGatewayData.php#L15).

It *does* remove it when using entries, but it obviously doesn't seem to work that way for database orders. It's not a huge issue.
