### ISSUE TITLE
Database order sorting broken after Runway upgrade (7.7.3 -> 7.8.0)

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#1143]
### Description

It looks like the ordering of database orders is broken when updating from Runway 7.7.3 to 7.8.0

#1056 improved the default ordering for database orders, but that is not working after upgrading Runway. Reverted back to 7.7.3 and the orders are sorted again. Not sure it this is the right repo to post, since it is probably related to some Runway changes between those versions.  

### Steps to reproduce

1. Upgrade runway to 7.8.0
2. Check database order listing and see the orders in wrong/random direction
<img width="388" alt="image" src="https://github.com/user-attachments/assets/7d2f4681-334e-4633-95d7-7dd3b35ba415">

### Environment

Version: 5.22.1 PRO

Addons:
aerni/advanced-seo: 2.9.0
aerni/font-awesome: 2.1.1
duncanmcclean/simple-commerce: 7.4.3
statamic-rad-pack/meilisearch: 3.3.0
statamic-rad-pack/runway: 7.8.0

**Comment by duncanmcclean** [comment]
I think this is a Runway bug. I've opened a bug report over there instead: statamic-rad-pack/runway#587.
