### ISSUE TITLE
Bug on coupon 

### ISSUE THREAD

**Issue by CodePranjal** [damcclean/simple-commerce#1149]
### Description

Hello I am using simple commerce. we've purchased it. The issue currently I am facing is with the coupon.
 
First I set a minimum payment margin to avail the coupon. works fine. 
I add product to cart, avail/redeem coupon. Now when I delete some product from the cart so total item value is now less than coupon mark. But still coupon is working.

Version we are on: 

statamic/cms": "^4.24"
simple-commerce": "^6.0"

**Comment by duncanmcclean** [comment]
This will be fixed in the next major version of Simple Commerce.
