### ISSUE TITLE
Cannot render an array variable as a string: {{ sc:cart:shipping_country }}

### ISSUE THREAD

**Issue by darinlarimore** [damcclean/simple-commerce#1165]
### Description

When using the Antlers tag  `{{ sc:cart:shipping_country }}` I receive an log message 
`Cannot render an array variable as a string: {{ sc:cart:shipping_country }}`

<img width="793" alt="Screenshot 2024-10-01 at 3 45 15 PM" src="https://github.com/user-attachments/assets/a2fd1e3a-7505-4dd8-989f-da5271dbd607">

### Steps to reproduce

1. Use Antlers tag `{{ sc:cart:shipping_country }}` in template.
2. See log message `Cannot render an array variable as a string: {{ sc:cart:shipping_country }}`
3. No shipping_country data is returned

### Environment

Environment
Application Name: Glass Arts Indiana
Laravel Version: 11.25.0
PHP Version: 8.3.10
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: glass-arts-indiana.test
Maintenance Mode: OFF
Timezone: America/Indiana/Indianapolis
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Simple Commerce
Currencies: USD
Gateways: Stripe
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: UPS Ground, UPS 2nd Day Air, UPS Next Day Air, No Shipping, Local Pickup
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.26.0 PRO

Statamic Addons
darinlarimore/simple-commerce-ups: 1.0.7
duncanmcclean/simple-commerce: 7.5.1
mitydigital/statamic-scheduled-cache-invalidator: 2.1.0
rias/statamic-redirect: 3.8.1
statamic/seo-pro: 6.1.2
trendyminds/guide: dev-main
trendyminds/link: dev-main
trendyminds/nerf: 1.2.0
trendyminds/statamic-palette: 1.2.1
trendyminds/tip: 1.0.0

**Comment by duncanmcclean** [comment]
Can you try `{{ sc:cart:shipping_country:name }}` and see if that works?

**Comment by darinlarimore** [comment]
~~That works! @duncanmcclean~~

Actually nvm I still get:
<img width="733" alt="Screenshot 2024-10-02 at 10 34 36 AM" src="https://github.com/user-attachments/assets/82c5a01a-ca5a-4e77-afe9-52bd56fe2baa">

**Comment by darinlarimore** [comment]
I also tried:
```
{{ sc:cart:shipping_country:raw }}
{{ sc:cart:shipping_country:name:value }}
{{ sc:cart:shipping_country:name:raw}}
{{ sc:cart:shipping_country:value }}
```
And received similar log messages.
<img width="862" alt="Screenshot 2024-10-02 at 10 37 35 AM" src="https://github.com/user-attachments/assets/ed1a3408-4b21-4e92-abcf-5b063fae5631">
