### ISSUE TITLE
Some Stripe webhooks failing due to missing order_id (manual Payment Links)

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#1176]
### Description

PaymentIntent webhooks from non-Simple Commerce sources (e.g. manually made Payment Links) are throwing errors due to missing `order_id` in `metadata`. Can be prevented by adding a check before each `method`-case and return 2x status code.

```
[2024-11-15 12:49:05] production.ERROR Undefined array key "order_id" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"order_id\" at /vendor/duncanmcclean/simple-commerce/src/Gateways/Builtin/StripeGateway.php:187)"}
```

Check if `metadata->order_id` exist
```php
if (!isset($data['metadata']['order_id'])) {
    return new Response('Webhook received but no order_id found', 202);
}
```

### Steps to reproduce

N/A

### Environment

N/A (let me know if needed)

**Comment by duncanmcclean** [comment]
The fix you've suggested looks good to me. Can you open a pull request?
