### ISSUE TITLE
Product variants not saving/showing data

### ISSUE THREAD

**Issue by maarten-mald-digital** [damcclean/simple-commerce#1185]
### Description

When changing variants price, saving, refreshing the values are not showing.

![Screenshot 2024-12-05 at 15 36 10](https://github.com/user-attachments/assets/a47ae2af-d7f2-42e5-b6c9-47dd84f4ccd1)
*before refresh

![Screenshot 2024-12-05 at 15 36 23](https://github.com/user-attachments/assets/8437b5f3-ffcc-4cd6-ab17-6fe2db9c1f9d)
*after refresh

### Steps to reproduce

1. Created clean statamic install using: "statamic new statamic-test"
2. Added package using: composer require duncanmcclean/simple-commerce
3. In blueprint removed "price" from collection "products" added "Product Variants"
4. Create Product > Add variants > add prices > save
5. Refresh, no data showing

### Environment

```
Environment
Application Name: Statamic
Laravel Version: 11.34.2
PHP Version: 8.3.13
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: statamic-test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Dummy
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 PRO

Statamic Addons
duncanmcclean/simple-commerce: 7.6.0
```

**Comment by duncanmcclean** [comment]
Is the data actually saved in the entry's markdown file?

**Comment by maarten-mald-digital** [comment]
@duncanmcclean yes

![Screenshot 2024-12-05 at 17 07 04](https://github.com/user-attachments/assets/57de3b20-9cde-4071-bd4e-1c734f460168)

**Comment by maarten-mald-digital** [comment]
@duncanmcclean yes. Added 111 and 222 and saved.

![Screenshot 2024-12-05 at 17 09 40](https://github.com/user-attachments/assets/1a7aa360-4e6c-4f24-8d1f-9bb091beca7a)

**Comment by duncanmcclean** [comment]
Thanks for checking!

**Comment by iC00kScripts** [comment]
Also experiencing this bug. But why is the variant field readonly? I can't find a way to make it editable

<img width="294" alt="Screenshot 2024-12-05 at 3 07 55 PM" src="https://github.com/user-attachments/assets/8a631124-ed9c-4b3b-a6ba-c06340db7373">

**Comment by duncanmcclean** [comment]
> But why is the variant field readonly?

The "Variant" field is generated as a combination of the variant options you configure above, eg `Red_Small`. It shouldn't be edited.

**Comment by iC00kScripts** [comment]
Oh. That makes sense. But it's not doing that either. On the product page, the variant dropdowns contains prices only.

**Comment by duncanmcclean** [comment]
Right - that can be fixed at the same time as this.

**Comment by iC00kScripts** [comment]
Thank you and well done!!
