### ISSUE TITLE
Issues with customer data check in PayPal webhook method

### ISSUE THREAD

**Issue by jacksleight** [damcclean/simple-commerce#471]
### Description

There seems to be a couple of bugs in the customer data check in the PayPal webhook method.

The first issue is that `! $order->customer() && $responseBody['payer']['name'] || $responseBody['payer']['email_address']` will always resolve true if `responseBody['payer']['email_address']` is set, even if there's an `$order->customer()`.

As the new customer code uses both `name` and `email_address` I assume the OR should really be an AND? If not `$responseBody['payer']['name'] || $responseBody['payer']['email_address']` should be wrapped in brackets.

The second issue is that `Customer::findByEmail()` throws a CustomerNotFound exception if it doesn't match, so that probably needs to be handled gracefully so the remaining code can execute.

These two issues combined mean that if the email address of the PayPal account doesn't match the order email address the webhook fails with a 500 error.

I was going to submit a PR but I wasn't sure how you'd want to handle the `Customer::findByEmail()` exception so I thought it was best to leave it to you.

### Steps to reproduce

1. Create a new order
2. Pay with PayPal using an account that doesn't match the order email address

### Environment

Statamic 3.2.5 Solo
Laravel 8.61.0
PHP 7.4.21
doublethreedigital/simple-commerce 2.3.29

**Comment by duncanmcclean** [comment]
Thanks for picking this up - I'll look into it this evening!

**Comment by duncanmcclean** [comment]
Fixed by 252247b7 & bc02a1be
