### ISSUE TITLE
Stock by variant

### ISSUE THREAD

**Issue by remiduval** [damcclean/simple-commerce#474]
### What would you like to see added?

At the moment, stock is only related to a product entry and not its variants.
It would be great to be able to specify the stock for each variant.

Example: I'm selling mugs - I have 40 items of the blue version and 50 items of the red version. At the moment, I would have to create 2 different product entries to specify the stock of each version.

### Is there a workaround you can use in the meantime?

Creating different product entries instead of using variants.

### Priority wise - where's this feature for you?

This is sort of a blocker for me/this project.

**Comment by duncanmcclean** [comment]
Thanks for opening an issue! I'll take a look when I have some time.

**Comment by duncanmcclean** [comment]
Released in [v2.3.43](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.43) 🚀 

Have a great weekend!

**Comment by remiduval** [comment]
Amazing - thank you so much!
