### ISSUE TITLE
Assets and toggle fieldtype not working in variants additional fields

### ISSUE THREAD

**Issue by WorldSeso7** [damcclean/simple-commerce#493]
### Bug Description

I added some additional fields to my product variants field in product blueprint and some of them are not working.
Text fields works as expected but:

- Assets fieldtype doesn't open the selector window (a javascript error is thrown on Selector.vue)
- Toggle fieldtype doesn't work. I click on the toggle but nothing happen and the toggle doesn't switch its state

### Steps to reproduce

1. Add some field to product variants fieldtype inside product blueprint

### Environment

Statamic 3.2.21 Pro
Laravel 8.70.2
PHP 7.4.14
doublethreedigital/simple-commerce 2.3.52

**Comment by duncanmcclean** [comment]
I had a look last night to try and track down the issue but couldn't figure it out - I won't have time to loop back to it now until the weekend.

However, sounds like your pull request solves the assets issue at least so that's good!

**Comment by duncanmcclean** [comment]
Released in [v2.3.53](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.53)
