### ISSUE TITLE
Open pricing

### ISSUE THREAD

**Issue by remiduval** [damcclean/simple-commerce#495]
### What would you like to see added?

Ability for the customer to set the price of the product he's buying.
Use case: donation with open pricing

### Is there a workaround you can use in the meantime?

- `open_price` toggle field in Product blueprint
- `amount` input field on Product page (gets saved as metadata)
- Using the [productPriceHook function](https://simple-commerce.duncanmcclean.com/kb-articles/dynamic-pricing)

```
SimpleCommerce::productPriceHook(function (Order $order, Product $product) {
	if ( !empty($product->data['open_price']) ) {
		foreach ( $order->data['items'] as $item) {
			if ($item['product'] == $product->id) {
				return $item['metadata']['amount'] * 100;
			}
		}
	} else {
		return $product->get('price');
	}
});
```

It's a bit hacky, and 2 issues:
1. Doesn't feel right to have to find the current product in the whole order (foreach loop above)
2. Won't work if multiple products with different open prices in basket
3. Price not displayed in cart line

### Priority wise - where's this feature for you?

Blocker

**Comment by duncanmcclean** [comment]
I'm unable to take a proper look until the weekend - however, from initial thinking, using the `productPriceHook` should work fine.

However, probably the way I'd do what you're asking (donations) would be to set the product price to £1, then let the user change the line item quantity. It would mean if the user wants to pay £15, the quantity of the line item would be 15. This really only works if you're allowing for whole amounts (eg. £15, not £14.58).

**Comment by remiduval** [comment]
Smart, I'll also look into the quantity idea then - I'll have to see how it's displayed in the cart so it's transparent for the customer.
Thank you!

**Comment by duncanmcclean** [comment]
> Smart, I'll also look into the quantity idea then - I'll have to see how it's displayed in the cart so it's transparent for the customer. Thank you!

No worries - hopefully that works for you.  I'll add this to the list of things to document. 👍
