### ISSUE TITLE
Product variant field issue 

### ISSUE THREAD

**Issue by vdelyanov** [damcclean/simple-commerce#497]
### What's the issue you're running into?

When I created an entry in the products collection, I got that -

![Screenshot 2021-12-01 at 9 10 26](https://user-images.githubusercontent.com/57762352/144194422-17aca26c-ca60-4a23-858c-de68cf49b0ef.png)

**"Product doesn't support variants"**

I am not sure how is supposed to work, I can't even find in the documentation that value input what type of field has to be and how is connecting with variant options. 

### Steps to reproduce

1. I Installed the addon
2. Then added a new key to the sites array in simple-commerce.php, because my site is multilanguage. (but that is not related to the problem, I think)
3. Edit Blueprint of the products collection and add Product variants and Product Variant. 

### Environment

Statamic 3.2.14 Pro
Laravel 8.63.0
PHP 7.4.21
doublethreedigital/simple-commerce 2.3.53

**Comment by duncanmcclean** [comment]
That fieldtype is used in the Order blueprint, under line items to select a specific variant on the selected product. You don't need to use it elsewhere.
