### ISSUE TITLE
Can't override receipt

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#499]
### Bug Description

When placing copies of templates in `resources/views`, the default templates are still being used by the addon:

`resources/views/vendor/doublethreedigital/simple-commerce`

![image](https://user-images.githubusercontent.com/10460870/145172872-18994652-ce26-4312-91d0-e351fb62fee4.png)

### Steps to reproduce

1. Duplicate `receipt.antlers.html`
2. Place it in `resources/views/vendor/doublethreedigital/simple-commerce`
3. Try the cart

### Environment

Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 7.4.26
doublethreedigital/simple-commerce 2.3.54
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.5

**Comment by duncanmcclean** [comment]
I don't have any time tonight to look into this but I'll hopefully get to it at some point this week/this weekend if that's alright?

**Comment by axelferdinand** [comment]
Sure, no worries!!

**Comment by duncanmcclean** [comment]
Ahh, I've figured it out....

The path to the receipt should be `resources/views/vendor/simple-commerce/receipt.antlers.html` (cut out the `doublethreedigital` folder)

That should do the job!

**Comment by axelferdinand** [comment]
That sure did work! Thank you so much!
