### ISSUE TITLE
Send receipt to store owner after cart checkout

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#500]
### What would you like to see added?

It would be awesome if also the store owner gets a copy of the receipt 🥳 

Store owners love receipts...

### Is there a workaround you can use in the meantime?

I tried your suggestion on Discord, but I didn't get it to work properly. I also tried adding `use Barryvdh\DomPDF\Facade as PDF;` on the top of the file.

`app/Notifications/BackOfficeOrderPaid.php`

```<?php

namespace App\Notifications;

use DoubleThreeDigital\SimpleCommerce\Contracts\Order;
use DoubleThreeDigital\SimpleCommerce\Facades\Currency;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Statamic\Facades\Site;
use Barryvdh\DomPDF\Facade as PDF;

class BackOfficeOrderPaid extends Notification
{
    use Queueable;

    protected $order;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(Order $order)
    {
        $this->order = $order;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return [
            'mail',
        ];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->subject("New Order: {$this->order->title()}")
            ->line("Order **{$this->order->title()}** is ready for fulfilment. WEEE")
            ->line("# Order Details")
            // ->line("Grand Total: " . Currency::parse($this->order->get('grand_total'), Site::current()))
            ->line("Items Total: " . Currency::parse($this->order->get('items_total'), Site::current()))
            // ->line("Shipping Total: " . Currency::parse($this->order->get('shipping_total'), Site::current()))
            ->line("Customer: " . optional($this->order->customer())->email() ?? 'Guest')
            >attachData(
                $pdf->output(),
                'receipt.pdf',
                ['mime' => 'application/pdf']
            );
    }
}
```

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Oh sorry, add this line before the `return (new MailMessage)` bit...

```
$pdf = PDF::loadView('simple-commerce::receipt', $this->order->toAugmentedArray());
```

Here's an example of it in the `CustomerOrderPaid` notification: https://github.com/doublethreedigital/simple-commerce/blob/2.3/src/Notifications/CustomerOrderPaid.php#L48

**Comment by axelferdinand** [comment]
Thank you, will try this! :D

**Comment by axelferdinand** [comment]
Got this error after trying this:

`Call to undefined function App\Notifications\attachData()`

![image](https://user-images.githubusercontent.com/10460870/145272170-be126a9e-d288-436e-872f-1fd5c73d7c80.png)

Any idea what I'm missing?

**Comment by axelferdinand** [comment]
Wait a minute!

I just missed a dash before `attachData(`

This is correct:
`->attachData(
                $pdf->output(),
                'receipt.pdf',
                ['mime' => 'application/pdf']
            );`

It works!!!

**Comment by duncanmcclean** [comment]
Fantastic!
