### ISSUE TITLE
Can't update cart items

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#501]
### Bug Description

When firing this form tag on the product page:

`{{ sc:cart:updateItem :item="id" }}
  <input type="number" name="quantity" value="2">
{{ /sc:cart:updateItem }}`

...I get this error:

`TypeError
Return value of DoubleThreeDigital\SimpleCommerce\Orders\Order::lineItem() must be of the type array, null returned`

![image](https://user-images.githubusercontent.com/10460870/145277423-deb9c3da-16d3-45c9-9148-2d3f72b38a9b.png)

However, this works perfectly:

```{{ sc:cart:addItem }}
  <input type="hidden" name="product" value="{{ id }}">
  <input type="number" name="quantity" value="2">
{{ /sc:cart:addItem }}```

### Steps to reproduce

1. Add the above form tag to a product page.
2. Fire the form.

### Environment

Statamic 3.2.25 Pro
Laravel 8.75.0
PHP 7.4.26
doublethreedigital/simple-commerce 2.3.54
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.5

**Comment by axelferdinand** [comment]
Ah, it has to be part of the cart loop...

```{{ sc:cart:items }}
        {{ product:title }} - {{ quantity }} - {{ total }}
{{ sc:cart:updateItem :item="id" }}
  <input type="number" name="quantity" value="2">
{{ /sc:cart:updateItem }}```

        {{ /sc:cart:items }}```

Shouldn't this also without being part of the loop?

**Comment by axelferdinand** [comment]
Nah, only this tag worked inside the loop:

`{{ sc:cart:removeItem :item="id" }}
  <button type="submit">Remove item from cart</button>
{{ /sc:cart:removeItem }}`

**Comment by duncanmcclean** [comment]
What is 'id'? Is it the ID of the product or the line item?

It should be of the line item.

**Comment by axelferdinand** [comment]
Correct! The line item.

**Comment by axelferdinand** [comment]
Or, wait – the product ID (I think) 

I'm not sure, actually...

**Comment by duncanmcclean** [comment]
Is there a possibility I can get access to your site to take a look at what you're doing? 

Either a zip or a repo invite would be fine - duncan@doublethree.digital.

If it's not possible, that's fine. We can try and continue on here...

**Comment by axelferdinand** [comment]
Sure! The view I’m working in is `product.antlers.html`

**Comment by duncanmcclean** [comment]
I don't see the `{{ sc:cart:updateItem }}` tag anywhere in that file...

**Comment by axelferdinand** [comment]
To seconds – let me push the things I've been working on!

**Comment by axelferdinand** [comment]
Check "new-master" branch now :)

**Comment by duncanmcclean** [comment]
Thanks! I'll take a proper look at it tonight 😅

**Comment by axelferdinand** [comment]
I'm trying to use a +/- counter to add/remove product items on the product page.

This would be the perfect scenario:
1. User clicks "Add to cart" and 1 item is added to the cart.
2. The +/- counter appears if 1 item is in cart, and "+" adds another item to the cart, "-" removes an item from the cart.

**Comment by axelferdinand** [comment]
Thanks, no rush!

**Comment by axelferdinand** [comment]
So, I'm much, much closer now. See the attached video.

https://user-images.githubusercontent.com/10460870/145407233-8a9e8106-dd4d-4735-a308-3280d1f46bcd.mov

The thing is, if you have a look at my `product.antlers.html` view, you will notice I loop through _all_ cart items to make this work, and that mixes all products together (if I navigate to another product, the counter is "stuck" with the first product I added) See the second attached video.

https://user-images.githubusercontent.com/10460870/145407664-75b20382-4038-4804-9b7b-6b26cf7b4b85.mov

I'm aware that my product view isn't set up correctly, I just don't know how to do it to make it work as expected.

**Comment by axelferdinand** [comment]
You can test the interaction here:

https://spa.prototypen.no/products/30130-aloe-vera-after-sun-gel-120-ml

**Comment by axelferdinand** [comment]
If Update Cart Item could work the same way as Add Cart Item, not being dependent of a loop, that would be perfect :)

```
{{ sc:cart:updateItem }}
  <input type="hidden" name="product" value="{{ id }}">
  <input type="number" name="quantity" value="2">
{{ /sc:cart:updateItem }}
```

just like

```
{{ sc:cart:addItem }}
  <input type="hidden" name="product" value="{{ id }}">
  <input type="number" name="quantity" value="2">
{{ /sc:cart:addItem }}
```

**Comment by duncanmcclean** [comment]
Finally had some time to take a look at this - sorry for the wait!

Just cloned down your site and read through the rest of your comments on this thread and you seemed to have got it sorted 🎉 

I'm not sure if it would be possible to get rid of the `id` parameter `{{ sc:cart:updateItem }}` as it would cause a breaking change. I actually quite like how it works right now - thanks for your suggestion though!

Closing as the issue has been resolved (I think?)

**Comment by axelferdinand** [comment]
Good evening!

I haven’t sorted it out quite yet, since the solution I have isn’t working as of now.

Try adding 2-3 different products to the cart, and then navigate to a product page. Then try adding another item to the cart, and notice how it’s the first (!) item in the cart that gets updated - not the actual product item you’re currently at 😅

**Comment by duncanmcclean** [comment]
Ohh okay. I think I might know how to workaround that… I’ll take a look again tomorrow.

**Comment by axelferdinand** [comment]
Thanks a ton!!

**Comment by axelferdinand** [comment]
If you remove the `{{ if first }}` condition, this will be the result:

![image](https://user-images.githubusercontent.com/10460870/145542020-0b798c66-9e8b-493e-ad01-df624fdee2c3.png)

**Comment by duncanmcclean** [comment]
https://user-images.githubusercontent.com/19637309/145816165-6d09f0fc-8807-44ae-b06d-effc37937729.mov

Is this how you're wanting it to work or I am I completely mis-understanding what you're meaning? If it's right, happy to push my changes up to your repo?

**Comment by axelferdinand** [comment]
PERFECT!!!

**Comment by duncanmcclean** [comment]
Pushed & closed 🚀

**Comment by axelferdinand** [comment]
Do I have to update the markup in my views? In that case, is the documentation updated?

**Comment by duncanmcclean** [comment]
I've committed my changes to your project. Essentially all I did was check if the current product in the loop is the current product:

```antlers
{{ sc:cart:items }}
  {{ if product:id === page:id }}
    <!-- The update stuff in here, as you had it before -->
  {{ /if }}
{{ /sc:cart:items }}
```

From what I can tell, there's only one place we use the `{{ sc:cart:items }}` tag which is for using on a cart page. However, I'll add this to my list of things to better document in the future (updating the quantity of the current product in the cart).

**Comment by axelferdinand** [comment]
Wow, thank you so much!!

**Comment by duncanmcclean** [comment]
No worries!!

**Comment by duncanmcclean** [comment]
Just so you know: this will be made a lot easier soon (when v3.2 is tagged), thanks to #644. The `updateItem` and `removeItem` tags will have a `product` parameter so you can do something like this instead:

```antlers
{{ sc:cart:updateItem :product="id" }}
  <input type="number" name="quantity" value="2">
{{ /sc:cart:updateItem }}
```

That'll save you looping through line items to find the right one to update 😅

**Comment by axelferdinand** [comment]
Thank you!!
