### ISSUE TITLE
Redirect checkout to ID

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#502]
### What would you like to see added?

It would be super nice if you could redirect the checkout to an ID (not just a solid URL).

This comes in handy when using the addon on a multisite, where the "thank you"-page is i many languages.

```
{{ sc:checkout redirect="e9454ba6-6319-43a7-a45d-b6be84e1c7a2" }}

      <input type="text" name="customer[name]" placeholder="Full Name">
      <input type="email" name="customer[email]" placeholder="Email">

      <select name="gateway" style="display:none;">
        {{ sc:gateways }}
        <option value="{{ class }}">{{ name }}</option>
        {{ /sc:gateways }}
      </select>

      <button type="submit">Order now</button>

      {{ /sc:checkout }}
```

### Is there a workaround you can use in the meantime?

Not that I know of.

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
I'd rather not complicate things with the `redirect` parameter if it's avoidable. 

I know it's ugly but would something like this work?

```antlers
{{ sc:checkout redirect="{{ get_content from="e9454ba6-6319-43a7-a45d-b6be84e1c7a2" }}{{ id }}{{ /get_content }}" }}
```

**Comment by axelferdinand** [comment]
I made this work:
`{{ sc:checkout redirect="{ receipt_page | get:url }" }}`

I just had to put the ID to the receipt page in my md-files 🙂 

Thanks!

**Comment by duncanmcclean** [comment]
Awesome!
