### ISSUE TITLE
Product Variants fieldtype variants fields not working

### ISSUE THREAD

**Issue by WorldSeso7** [damcclean/simple-commerce#503]
### Bug Description

When creating a new product with variants some fieldtype of the option fields are not working correctly. The fieldtypes are assets and toggle.
When creating the product the assets fieldtype gives a js error and the toggle is not clickable. If you save the product and refresh the cp page the assets fieldtype let the user to select the assets and the toggle fieldtype works as expected.

### Steps to reproduce

1. Create a new product with variant with assets and toggle fieldtypes as option fields.
2. Add a variant with some options
3. Click on the assets fieldtype or on the toggle fieldtype

### Environment

Statamic 3.2.25 Pro
Laravel 8.75.0
PHP 7.4.14
doublethreedigital/simple-commerce 2.3.54

**Comment by duncanmcclean** [comment]
If you rollback to `v2.3.52`, is the problem fixed for you or do you get the same issue?

**Comment by duncanmcclean** [comment]
I actually thought we fixed this issue recently but seems like we didn't 😢 

I've got the week off next week so I'll take a proper look then.

**Comment by duncanmcclean** [comment]
Hmm, I'm actually unable to reproduce this bug.

Would you be able to run `php artisan statamic:install` which will re-publish Simple Commerce's JS files and can you try a hard refresh in your browser (or try a different browser altogether)?

**Comment by WorldSeso7** [comment]
Hi Duncan! Thank you for the effort you're taking to investigate this issue.
I registered a screencast with the various behaviour I'm experiencing related to this issue.
Here you can find the video https://debian.adacto.it/screencast-simple-commerce-statamic-bug.mp4

**Comment by duncanmcclean** [comment]
Ohh, I see it now. Looks like it's only an issue when new variations are created. After saving a variation, the toggle/asset fieldtypes work properly... 🤔

**Comment by duncanmcclean** [comment]
Will be fixed in the next release.
