### ISSUE TITLE
Tags "total" and "grand_total" outputs the same value

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#504]
### Bug Description

Shouldn't it be a difference in output from these two tags?

**Total**
Displays the total without taxes.

`{{ sc:cart:total }}`

**Grand total**
Displays the total including taxes.

`{{ sc:cart:grand_total }}`

### Steps to reproduce

Test the tags :) 

### Environment

Statamic 3.2.25 Pro
Laravel 8.75.0
PHP 7.4.26
doublethreedigital/simple-commerce 2.3.54
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.5

**Comment by duncanmcclean** [comment]
`total` is an alias of `grand_total`. If you want the total of just the items without tax, use `items_total`.

**Comment by axelferdinand** [comment]
Thanks!!
