### ISSUE TITLE
Can't add name attr to form tag

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#505]
### Bug Description

It seems like the SC form tags don't accept `name attr`:

`{{ sc:checkout class="form" data-ng-controller="form" id="checkoutform" name="checkoutform" data-custom-submit="submit(checkoutform)" redirect="{ receipt_page | get:url }" }}`

Returns:

`<form method="POST" action="http://localhost:5757/!/simple-commerce/checkout" class="form" data-ng-controller="form" id="checkoutform" data-custom-submit="submit(checkoutform)" novalidate="novalidate">`

### Steps to reproduce

See above :)

### Environment

Statamic 3.2.25 Pro
Laravel 8.75.0
PHP 7.4.26
doublethreedigital/simple-commerce 2.3.54
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.5

**Comment by duncanmcclean** [comment]
Thanks for reporting! 

I think I must have copied the form tag code from elsewhere and it was stripping out the 'name' parameter. It'll be fixed in the next release. Enjoy your weekend!

**Comment by axelferdinand** [comment]
Great news! When will this update be pushed? I can't make my JS validate the form without the name attribute.

**Comment by duncanmcclean** [comment]
Working through all the Simple Commerce issues today - will release it once I'm done with them!

**Comment by axelferdinand** [comment]
That is super! Thank you, Duncan!
