### ISSUE TITLE
Stock is not decreased after successful order

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#506]
### Bug Description

We have a product with 1 on stock. _(Field with handle stock within the product blueprint)_

![image](https://user-images.githubusercontent.com/81617758/145672616-471840ee-d715-4fe2-ac96-0b2b0f7197bf.png)

After checkout of 1 product we would expect that the stock is set to 0. This doesn't happen and the product stays available in the catalog.

### Steps to reproduce

1. Add a product with 1 for stock.
2. Go to the catalog and select this product.
3. In the detail view of the product add it to the cart.
4. Click on 'Go to checkout' in the cart view (see Image Checkout).
5. Fill in the personal information and click on Pay.
_(We skip the part of shipping, for this we update the shipping costs in the backend through the _OrderSaved_ event.)_.
7. We are redirected to Mollie where we execute the payment.
8. We come back to the shop with a success.
9. In the CP the order has been paid and contains our product with quantity of 1 (see Image Order CP).
8. After coming back to the shop the product is still available in the cp and stock in cp is 1.

**Image checkout**
![image](https://user-images.githubusercontent.com/81617758/145673136-194d5ff0-a334-4a0b-a761-7f81cc316a60.png)

**Image Order CP**
![image](https://user-images.githubusercontent.com/81617758/145673409-0b89d3b6-0f7c-4849-8918-4247303ec29f.png)

### Environment

Local dev environment:
- Statamic 3.2.22 Pro
- Laravel 8.73.1
- PHP 7.4.20
- doublethreedigital/simple-commerce 2.3.54
- gioppy/statamic-metatags 1.0.4
- joetannenbaum/antlers-stack-tags 0.1.0

**Comment by duncanmcclean** [comment]
Note to self: this is only an issue when the customer checks out using an off-site gateway (like Mollie/PayPal)

**Comment by duncanmcclean** [comment]
Will be fixed in the next release - probably later today!

**Comment by itsmesaskovic** [comment]
Thank you for this quick fix! 💪
We can confirm that it works now as expected.
