### ISSUE TITLE
Cart update seems to be connected to site language

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#512]
### Bug Description

Have a look at the following screen recording:

https://user-images.githubusercontent.com/10460870/145958020-509c0639-222c-4474-9501-36255827e458.mov

When changing the site language, these conditions don't seem to work anymore:

```
<div class="counter">
            {{ sc:cart:items }}
                {{ if product:id === page:id }}
                    {{ if quantity == "1" }}
                        {{ sc:cart:removeItem :item="id" }}
                            <button class="counter__button counter__button--decrease" type="submit"><i class="icon icon-minus"></i></button>
                        {{ /sc:cart:removeItem }}
                    {{ else }}
                        {{ sc:cart:updateItem :item="id" }}
                            <input type="number" name="quantity" data-ng-value="{{ quantity }} - 1" style="display:none;">
                            <button class="counter__button counter__button--decrease" type="submit"><i class="icon icon-minus"></i></button>
                        {{ /sc:cart:updateItem }}
                    {{ /if }}
                {{ /if }}
            {{ /sc:cart:items }}

            {{ sc:cart:items }}
                {{ if product:id === page:id }}
                    {{ if quantity >= "1" }}
                        <input class="counter__input" type="number" name="quantity" id="quantity" data-ng-init="{{ quantity }} = 1" data-ng-model="{{ quantity }}" required disabled>
                    {{ /if }}
                {{ /if }}
            {{ /sc:cart:items }}

            {{ sc:cart:items }}
                {{ if product:id === page:id }}
                    {{ sc:cart:updateItem :item="id" }}
                        <input type="number" name="quantity" data-ng-value="{{ quantity }} + 1" style="display:none;">
                        <button class="counter__button counter__button--increase" type="submit"><i class="icon icon-plus"></i></button>
                    {{ /sc:cart:updateItem }}
                {{ /if }}
            {{ /sc:cart:items }}
          </div>
```

Any idea what goes wrong here?

### Steps to reproduce

1. Add something to the cart with the above markup.
2. Change the site language.

### Environment

Statamic 3.2.26 Pro
Laravel 8.75.0
PHP 7.4.26
aryehraber/statamic-captcha 1.7.0
doublethreedigital/simple-commerce 2.3.56
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.5

**Comment by axelferdinand** [comment]
I believe it's this check that causes the issue:
`{{ if product:id === page:id }}`

Since each product language has its own unique ID – is there another way of targeting the same product, regardless of language?

**Comment by axelferdinand** [comment]
I assume I can just use the article number, which is unique to the product, but not unique to the language.

This works:
`{{ if product:art === page:art }}`

**Comment by duncanmcclean** [comment]
Oh, are you accessing the same cart between sites? 

So you added a product in English, then visited the product in German and the IDs didn't match up? (languages are just an example)

In theory, each 'site' should be it's own store (as they can have different shipping methods, different currencies, different tax rates). Therefore, they should have their own carts. However, thinking about it, I don't think we're actually doing that (the cart per site bit).

**Comment by axelferdinand** [comment]
Yeah, the customer can chose to select another language.

If you live in Norway, but don't speak Norwegian, you can select English as language, and still order the products to Norway.

But `{{ if product:art === page:art }}` works perfectly fine, so you can close this ticket :)

**Comment by duncanmcclean** [comment]
Okay, I'll close this issue now.
