### ISSUE TITLE
ErrorException: Undefined property: DOMAttr::$value

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#513]
### Bug Description

When going through checkout on my server, I get this error:

`ErrorException: Undefined property: DOMAttr::$value`

See the below screenshot.

![image](https://user-images.githubusercontent.com/10460870/145961049-dab9d969-f151-4a7d-8e80-62b38f9765e5.png)

### Steps to reproduce

1. Go through checkout on server

### Environment

Statamic 3.2.26 Pro
Laravel 8.75.0
PHP 7.4.26
aryehraber/statamic-captcha 1.7.0
doublethreedigital/simple-commerce 2.3.56
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.5

**Comment by duncanmcclean** [comment]
Looks like that's coming from the package we use to generate the receipt PDFs...

Has the receipt worked before on that server?

**Comment by axelferdinand** [comment]
I'm not 100% sure, but I believe so, yes.

It's working perfectly fine on my local – should I ask my server host about this?

**Comment by duncanmcclean** [comment]
I'm away from the computer today - if it works locally, id suggest doing a Google to see if anyone has ran into a similar issue. 

It's not an error I've seen before. I can't see what SC would be doing to break it 😆

**Comment by duncanmcclean** [comment]
I've found a couple of related GitHub issues when I did a Google:

* https://github.com/barryvdh/laravel-dompdf/issues/692
* https://github.com/dompdf/dompdf/issues/1549
* https://stackoverflow.com/questions/43846394/dompdf-get-undefined-property-domtextdata

Everyone also seems to be only able to reproduce on a server, not in their local environments. 

As it seems like it's not really a Simple Commerce issue (but rather one with a dependency SC uses), I'm going to close this issue. Although, if you figure it out, would love to know how you managed to fix it!

**Comment by axelferdinand** [comment]
I been talking back and forth with my hosting provider, and they have read through and tested all the resources you referred to, without luck. 

Here's a few of their comments:
"We cannot not see anything that is directly missing in server config. libxml and iconv are installed and according to the documentation on php.net this is all that is required to use DOM in php."

"The fact that we get identical errors on both php 7.4 and php 8.0, indicates that there is nothing wrong with the php installation itself. But it may be that something is missing, but it is not something we can see from the error message."

Did any of the other Simple Commerce users solve this issue?

**Comment by duncanmcclean** [comment]
No other Simple Commerce customers have ever ran into this. Never had any problems with the library before.

**Comment by axelferdinand** [comment]
Ah, thought you said earlier that some users ran into this. I misunderstood :)

**Comment by duncanmcclean** [comment]
I've just spun up a server with Laravel Forge to test this myself and I didn't run into the issue... it does seem like a hosting issue I'm afraid. 

Who are you hosting with?

**Comment by axelferdinand** [comment]
Yeah, I guess you're right.. I'm using https://sircon.no/ – a Norwegian host. I have 50+ websites there.

**Comment by duncanmcclean** [comment]
So, under the hood the receipts are generated with the [DomPDF](https://github.com/dompdf/dompdf) library, which has a list of requirements:

```
* PHP version 7.1 or higher
* DOM extension
* MBString extension
* php-font-lib
* php-svg-lib
```

If you look at the output of PHPInfo (Control Panel -> Utilities -> PHP Info), there should be sections for both `DOM` and `MBString`, here's what those sections look like for me, on my Forge server:

![image](https://user-images.githubusercontent.com/19637309/146370540-011267da-4535-4408-8d62-91fe91db525b.png)

![image](https://user-images.githubusercontent.com/19637309/146370579-9b573b8b-b088-4ba2-bbd6-8238a7fcb106.png)

**Comment by axelferdinand** [comment]
Here's what it looks like on my server:
![image](https://user-images.githubusercontent.com/10460870/146371016-22089e93-2386-424c-a465-9556065215fe.png)

![image](https://user-images.githubusercontent.com/10460870/146371058-9bacc0f2-682c-4721-9fcf-e9ce43387604.png)

**Comment by duncanmcclean** [comment]
They look pretty similar to me... 

I'm not really sure where to look from here unfortunately, I'm not much of a server person. I just let Forge do everything for me 😅  

I understand it's a bit of a pain for you though 🤔

**Comment by axelferdinand** [comment]
I get it 😅 Hopefully my host figures this out. Thanks for your help!

**Comment by axelferdinand** [comment]
Just a quick question – are these two requirements included by your addon?

`php-font-lib`
`php-svg-lib`

When it comes to the other requirements, these are all met by the server.

**Comment by duncanmcclean** [comment]
They're requirements of DomPDF, I couldn't find anything about them in my 'PHP Info' output but I presume they're installed somewhere.

I have a feeling that if you didn't have them, you'd be running into a different error (or the receipt output would just be broken) 😅
