### ISSUE TITLE
After payment @Mollie the webhook fails with a product that started with stock == 1

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#514]
### Bug Description

Upon coming back from Mollie an error is thrown from the Webhook.

[2021-12-15 14:24:10] local.ERROR: Product [75bd00a7-76bd-41f3-9900-a91ffe2ecbe9] does not have any available stock. {"exception":"[object] (DoubleThreeDigital\SimpleCommerce\Exceptions\CheckoutProductHasNoStockException(code: 0): Product [75bd00a7-76bd-41f3-9900-a91ffe2ecbe9] does not have any available stock. at D:\dev\xampp\
ofam-web-peak\vendor\doublethreedigital\simple-commerce\src\Checkout\HandleStock.php:27)
[stacktrace]
#0 D:\dev\xampp\
ofam-web-peak\vendor\laravel\framework\src\Illuminate\Collections\Traits\EnumeratesValues.php(242): DoubleThreeDigital\SimpleCommerce\Gateways\BaseGateway->DoubleThreeDigital\SimpleCommerce\Checkout\{closure}(Array, 0)
#1 D:\dev\xampp\
ofam-web-peak\vendor\doublethreedigital\simple-commerce\src\Checkout\HandleStock.php(64): Illuminate\Support\Collection->each(Object(Closure))
#2 D:\dev\xampp\
ofam-web-peak\vendor\doublethreedigital\simple-commerce\src\Gateways\BaseGateway.php(107): DoubleThreeDigital\SimpleCommerce\Gateways\BaseGateway->handleStock(Object(DoubleThreeDigital\SimpleCommerce\Orders\Order))
#3 D:\dev\xampp\
ofam-web-peak\vendor\doublethreedigital\simple-commerce\src\Gateways\Builtin\MollieGateway.php(128): DoubleThreeDigital\SimpleCommerce\Gateways\BaseGateway->markOrderAsPaid(Object(DoubleThreeDigital\SimpleCommerce\Orders\Order))
#4 D:\dev\xampp\
ofam-web-peak\vendor\doublethreedigital\simple-commerce\src\Gateways\Manager.php(95): DoubleThreeDigital\SimpleCommerce\Gateways\Builtin\MollieGateway->webhook(Object(Illuminate\Http\Request))
#5 D:\dev\xampp\
ofam-web-peak\vendor\doublethreedigital\simple-commerce\src\Http\Controllers\GatewayWebhookController.php(27): DoubleThreeDigital\SimpleCommerce\Gateways\Manager->webhook(Object(Illuminate\Http\Request))

### Steps to reproduce

1. Checkout a product with stock == 1;
2. Fulfill the test payment @Mollie;
3. Upon coming back stock is set to 0 and the above error is logged.

### Environment

Statamic 3.2.26 Pro
Laravel 8.76.1
PHP 7.4.20
doublethreedigital/simple-commerce 2.3.56
gioppy/statamic-metatags 1.0.4
joetannenbaum/antlers-stack-tags 0.1.0

**Comment by duncanmcclean** [comment]
Closing as this seems to have sorted itself out after restarting the Ngrok tunnel (discussed via Discord)
