### ISSUE TITLE
Translate countries in other languages

### ISSUE THREAD

**Issue by steffenschmidt** [damcclean/simple-commerce#522]
### What's the issue you're running into?

Hi,

currently the countries list used for shipping and billing address is a static list. Is there a way to translate or overwrite these values? I could change this directly in the file (src/Support/Countries.php), but this would not be in the sense of the inventor.

Cheers
Steffen

### Steps to reproduce

1. Use starter-kit
2. Set locales to German oder any other language than English
3. Add some products to your cart
4. Start checkout process
5. Use country selector

Here I would like to see translated names, not by default but by translation file or something else.

### Environment

Statamic 3.2.27 Solo
Laravel 8.76.2
PHP 8.1.0
aryehraber/statamic-logbook 2.0.2
doublethreedigital/simple-commerce 2.3.57
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
Thanks for bringing this up! 

If you update to the latest version of Simple Commerce, **v2.3.58**, you will be able to specify translations for country names.

1. Create a JSON translations file for your locale, in `resources/lang` - eg. `resources/lang/en.json`
2. Inside the file, specify the original country name, then your translated version of the country name:

```json
{
    "United Kingdom": "The UK"
}
```

Hopefully that should do what you need!

**Comment by steffenschmidt** [comment]
Thanks for the quick help!

**Comment by duncanmcclean** [comment]
No problem!
