### ISSUE TITLE
Can the 'money' fieldtype support multiple locales in CP?

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#523]
### What would you like to see added?

As of now, it appears that the `money` fieldtype supports multiple locales only in the front-end. Can support be extended to the CP as well? So the editor will see the correct currency when working with prices if different locales?

https://user-images.githubusercontent.com/10460870/147931349-b6190eb2-5f71-41be-9903-b78681541579.mov

### Is there a workaround you can use in the meantime?

Not that I know of.

### Priority wise - where's this feature for you?

Nice to have

**Comment by duncanmcclean** [comment]
I'll take a look - it _should_ already be adjusting based on current site but obviously not 😆

**Comment by axelferdinand** [comment]
Fantastic! That was fast!

**Comment by duncanmcclean** [comment]
Haha, it was a fast fix! I'll release it later today - got a few more changes I want to make before then.
