### ISSUE TITLE
Checkout input elements don't support type="hidden"

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#528]
### Bug Description

It seems that checkout form input elements need to be hidden using CSS, when adding the attribute `type="hidden"` prevents the input values from being stored.

### Steps to reproduce

1. Change input type to hidden in checkout
2. Submit an order
3. Check the customer/order files

### Environment

Statamic 3.2.28 Pro
Laravel 8.77.1
PHP 7.4.26
aryehraber/statamic-captcha 1.7.0
doublethreedigital/duplicator 2.0.1
doublethreedigital/simple-commerce 2.3.58
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
Using `type="hidden"` on inputs should absolutely work. Can you share an example of what you're doing?

**Comment by axelferdinand** [comment]
This works:

```
<input class="o-hide" name="customer[name]" data-ng-model="input.name_first" />
<input class="o-hide" name="customer[name_first]" data-ng-model="input.name_first" />
```

This doesn't work (on my computer, haha):
```
<input name="customer[name]" type="hidden" data-ng-model="input.name_first" />
<input name="customer[name_first]" type="hidden" data-ng-model="input.name_first" />
```

**Comment by duncanmcclean** [comment]
Before I investigate further, does it work if you try it on a plain page with no Angular (I presume that's the `data-ng` bit) stuff?

**Comment by axelferdinand** [comment]
My bad... Angular is the problem here!

**Comment by duncanmcclean** [comment]
No worries - thought I would ask before I start pulling my hair out 😆
