### ISSUE TITLE
Locale if conditions fails within {{ sc:cart }} array

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#532]
### Bug Description

If you try to translate the cart to multiple languages, using if conditions on locale, only the default language shows – regardless of which locale is set.

```
{{ sc:cart }}
{{ items }}

{{ product:title }}

{{ if locale == "no" }}Fjern fra handlekurv{{ elseif locale == "se" }}Ta bort från vagnen{{ elseif locale == "fi" }}Poista ostoskorista{{ else }}Remove from cart{{ /if }}

{{ /items }}
{{ /sc:cart }}
```

Moving the if condition _outside_ of the array, works perfectly fine, however.

### Steps to reproduce

See description above :)

### Environment

Statamic 3.2.29 Pro
Laravel 8.78.0
PHP 7.4.26
aryehraber/statamic-captcha 1.7.0
doublethreedigital/duplicator 2.1.0
doublethreedigital/simple-commerce 2.3.59
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
If you do `{{ locale | dump }}` inside and out of `{{ sc:cart }}`, what do you get?

**Comment by duncanmcclean** [comment]
Also, does it behave properly if you do this instead?

```
{{ sc:cart:items }}

{{ product:title }}

{{ if locale == "no" }}Fjern fra handlekurv{{ elseif locale == "se" }}Ta bort från vagnen{{ elseif locale == "fi" }}Poista ostoskorista{{ else }}Remove from cart{{ /if }}

{{ /sc:cart:items }}
```

**Comment by axelferdinand** [comment]
The last solution worked! Thanks a ton, Duncan!!

**Comment by duncanmcclean** [comment]
No worries! It's because you get the whole 'augmented' entry when you're inside `{{ sc:cart }}`, which includes it's overridden `locale`. 

I'll close this as it's avoidable with the provided solution.
