### ISSUE TITLE
Recaptcha addon doesn't apply to the checkout form

### ISSUE THREAD

**Issue by axelferdinand** [damcclean/simple-commerce#533]
### Bug Description

I'm using this addon on all my Statamic forms:

https://github.com/aryehraber/statamic-captcha

![image](https://user-images.githubusercontent.com/10460870/148412735-0145eba6-f05b-45e7-b829-69c26c9c8ea4.png)

But when I tried submitting the checkout form in Simple Commerce _without_ checking the captcha box, it submitted just fine (which isn't fine, haha)

I'm using this checkout form:

```
{{ sc:checkout class="form" id="checkoutform" name="checkoutform" test="checkoutform" data-custom-submit="submit(checkoutform)" redirect="{ confirmation_page | get:url }" }}

<!-- Inputs ––>

{{ captcha }}

{{ /sc:checkout }}
```

### Steps to reproduce

See description above :)

### Environment

Statamic 3.2.29 Pro
Laravel 8.78.0
PHP 7.4.26
aryehraber/statamic-captcha 1.7.0
doublethreedigital/duplicator 2.1.0
doublethreedigital/simple-commerce 2.3.59
jacksleight/bard-paragraph-style 1.2.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
Simple Commerce doesn't support that addon and I don't think there is a way to make it support it - as it's tied to Statamic's Forms feature which SC doesn't use.

I think you'd be better pulling in a Laravel Recaptcha package, then use the Recaptcha package in a [Laravel Form Request](https://laravel.com/docs/master/validation#creating-form-requests) to validate the Recaptcha has been filled in. You can provide the [`request`](https://simple-commerce.duncanmcclean.com/tags#content-form-tags) parameter to specify the Form Request you wish to use.

**Comment by axelferdinand** [comment]
Thanks, I'll look into it!

**Comment by duncanmcclean** [comment]
Closing this issue now - would love to know how you get on though!
