### ISSUE TITLE
Error during checkout after upgrade from 2.3.15 to 2.3.59

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#534]
### Bug Description

Upgrade from 2.3.15 to 2.3.59 throws error on checkout page.

`
Could not check compatibility between App\ShippingMethods\Pickup::checkAvailability(DoubleThreeDigital\SimpleCommerce\Data\Address $address): bool and DoubleThreeDigital\SimpleCommerce\Contracts\ShippingMethod::checkAvailability(DoubleThreeDigital\SimpleCommerce\Orders\Address $address): bool, because class DoubleThreeDigital\SimpleCommerce\Data\Address is not available
`

this is my  ShippingMethod:
```
<?php

namespace App\ShippingMethods;

use DoubleThreeDigital\SimpleCommerce\Contracts\Order;
use DoubleThreeDigital\SimpleCommerce\Contracts\ShippingMethod;
use DoubleThreeDigital\SimpleCommerce\Data\Address;

class Pickup implements ShippingMethod
{
    public function name(): string
    {
        return 'Gratis afhalen in Hellendoorn';
    }

    public function description(): string
    {
        return 'Aafhalen bij Beefs And Beers afhaalcafe in Hellendoorn';
    }

    public function calculateCost(Order $order): int
    {
        return 0;
    }

    public function checkAvailability(Address $address): bool
    {
        return true;
    }

}
```

### Steps to reproduce

Upgrade from  from 2.3.15 to 2.3.59  and do a checkout

### Environment

Statamic 3.2.29 Solo
Laravel 8.78.1
PHP 7.4.13
cnj/seotamic 2.0.5
doublethreedigital/duplicator 2.1.0
doublethreedigital/simple-commerce 2.3.59
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
If you change this:

```php
use DoubleThreeDigital\SimpleCommerce\Data\Address;
```

to this:

```php
use DoubleThreeDigital\SimpleCommerce\Orders\Address;
```

In your `Pickup` shipping method, does that get rid of the error?

I honestly have no idea how that was working for you on Simple Commerce v2.3.15, as that was something that was changed in v2.2 - [see change](https://github.com/doublethreedigital/simple-commerce/pull/326/files#diff-11326f53be2d93ea8942a09fff8f086dacc1efb13b8bd2ac637b0728f82374d9).

**Comment by studiovlijmscherp** [comment]
Fixed!  Thanks 🥳

**Comment by duncanmcclean** [comment]
Awesome!
