### ISSUE TITLE
PostCheckout fails for Mollie Gateway

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#535]
### Bug Description

After a successful payment Mollie makes a call to the webhook which triggers the PostCheckout event.
In 2.3.59 this fails:

`"POST /!/simple-commerce/gateways/mollie/webhook HTTP/1.1" 500 6634 "-" "Mollie HTTP client/1.0"`

The error shown in the logs:
`Too few arguments to function DoubleThreeDigital\SimpleCommerce\Events\PostCheckout::__construct(), 1 passed in /var/www/nofam-acc/vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/MollieGateway.php on line 130 and exactly 2 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function DoubleThreeDigital\\SimpleCommerce\\Events\\PostCheckout::__construct(), 1 passed in /var/www/nofam-acc/vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/MollieGateway.php on line 130 and exactly 2 expected at /var/www/nofam-acc/vendor/doublethreedigital/simple-commerce/src/Events/PostCheckout.php:17)`

A side effect of this is that upon a successful payment and callback Mollie receives a 500 error and tries again. This results in setting the order to paid (again) and sending an order paid mail (again). Can lead to a full inbox... ;-)

### Steps to reproduce

1. Configure Simple Commerce to use Mollie as a payment provider
2. Add products to your cart
3. Go through the payment process
4. Successfully pay the order in Mollie
5. Upon callback the error is thrown in the server.

### Environment

Statamic 3.2.28 Pro
Laravel 8.77.1
PHP 7.4.20
doublethreedigital/simple-commerce 2.3.58
gioppy/statamic-metatags 1.0.4
joetannenbaum/antlers-stack-tags 0.1.0

**Comment by duncanmcclean** [comment]
Thanks, will be fixed in the next release.
