### ISSUE TITLE
Fieldtype [variants] not found 

### ISSUE THREAD

**Issue by devravik** [damcclean/simple-commerce#543]
### Bug Description

Statamic\Exceptions\FieldtypeNotFoundException
Fieldtype [variants] not found 

![image](https://user-images.githubusercontent.com/41594847/149189852-3b3b2516-65d5-4417-8b74-38a1ab784f77.png)

### Steps to reproduce

Just installed Addon and Ran php please sc:install

On accessing Collection > Products from CP getting this error.

### Environment

Statamic 3.2.30 Pro
Laravel 8.79.0
PHP 7.4.27
doublethreedigital/simple-commerce 2.3.62
spatie/statamic-responsive-images 2.8.5
statamic/seo-pro 2.3.2
xndbogdan/statamic-bard-text-color 2.2

**Comment by duncanmcclean** [comment]
Hmm, I don't have any time to look into this tonight..

But if you change 'variants' to 'product_variants' in the Product blueprint, does that fix the issue?

**Comment by devravik** [comment]
> 
Changing 'variants' to 'product_variants' in the Product blueprint fixed that issue but now having a new error.
 
` Fieldtype [disabled_text] not found `
 
![image](https://user-images.githubusercontent.com/41594847/149198028-fa3e9b96-93f9-4889-b2e1-4c58bd9b828c.png)

**Comment by duncanmcclean** [comment]
Is this on an existing site?

**Comment by devravik** [comment]
Yes

**Comment by duncanmcclean** [comment]
I don't think this is a Simple Commerce issue.

**Comment by duncanmcclean** [comment]
See my comment on the other issue. I don't believe this is a Simple Commerce issue.

**Comment by duncanmcclean** [comment]
Closing this as I believe the Shopify addon has previously been installed and was then uninstalled, leaving behind it's fields in Blueprints etc.
