### ISSUE TITLE
There were some errors with your submission

### ISSUE THREAD

**Issue by devravik** [damcclean/simple-commerce#545]
### Bug Description

![image](https://user-images.githubusercontent.com/41594847/149375551-6554a7ed-dd02-496b-9cfb-4287e042f350.png)

### Steps to reproduce

While finishing checkout with Stripe

### Environment

Statamic 3.2.30 Pro
Laravel 8.79.0
PHP 7.4.27
doublethreedigital/simple-commerce 2.3.62
spatie/statamic-responsive-images 2.8.5
statamic/seo-pro 2.3.2
xndbogdan/statamic-bard-text-color 2.2

**Comment by duncanmcclean** [comment]
Closing as this has been fixed on Discord - Stripe Elements wasn't setting the `payment_method`
