### ISSUE TITLE
Users can add more quantity for a single product to the cart than available

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#548]
### Bug Description

When a user clicks on the submit button multiple times this product is also added multiple times to the cart. At this moment there is no check on available stock to see if the product is available that much.

Our code:
```
  {{ sc:cart:addItem class="border-t border-gray-200 py-4 flex justify-between items-center" redirect="/shop/cart" }}
                            <input type="hidden" name="product" value="{{ id }}">
                            <input type="hidden" name="shipping_method" value="{{verzendmogelijkheid}}{{title}}{{/verzendmogelijkheid}}">
                            <input type="hidden" name="quantity" value="1">
                            <button type="submit" class="cta-btn focus:outline-none">{{ trans:strings.add_to_cart }}</button>
                            {{ /sc:cart:addItem }}
```

We tried blocking the submit with Alpinejs but it blocks the entire submission of the form.
On the other side we would expect this blocked by SimpleCommerce, since a check can be done on backend to see if there is any stock available for the same product.

### Steps to reproduce

1. Set the product quantity in the CP to 1
2. Open the product (show) page of the specific product
3. Click three times on the submit button
4. Wait for the cart to load
5. Product has been added 3x to the cart

### Environment

Statamic 3.2.30 Pro
Laravel 8.77.1
PHP 7.4.20
doublethreedigital/simple-commerce 2.3.62
gioppy/statamic-metatags 1.0.4
joetannenbaum/antlers-stack-tags 0.1.0
roorda-ict/statamic-entries-export 1.0.0

**Comment by duncanmcclean** [comment]
Hmm, I thought we were already checking for stock when adding to the cart. I'll check when I have some free time.

**Comment by duncanmcclean** [comment]
Oh, I see what you mean. It only happens if you click the 'Add to cart' button multiple times... 

If you provide a quantity selector on the 'add to cart' form and select more than the product has stock for, an error is thrown then.

I suspect this will take some digging which I probably won't have time for until the weekend - I hope that's okay?

**Comment by itsmesaskovic** [comment]
No problem. I've implemented a short term solution through an event. It's
hard-coded to 1 now since we are selling unique second hand books.

Take your time and thanks for the effort!

Cheers, Saša

Op di 18 jan. 2022 23:16 schreef Duncan McClean ***@***.***>:

**Comment by duncanmcclean** [comment]
So I've been thinking about this over the past week - trying to decide whether it's something SC can fix or if it's something that can be fixed client-site.

I've ended up at the conclusion that it's something that can be fixed client-site with JavaScript. Ideally, to prevent this from happening, you would disable the button after the users' initial click. 

If you didn't disable the button, a stock check would still happen during the checkout process and the order wouldn't go through if there's not enough stock available.

For those reasons: I'm going to close this issue. Thanks for creating this though!
