### ISSUE TITLE
Order paid notification e-mails are being sent multiple times

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#554]
### Bug Description

When a customer orders and pays an 'Order paid notification e-mail'  should be sent. This works, however the mail is sent multiple times (some with several minutes between them). One customer received a total of 9 mails:

<img width="1088" alt="Schermafbeelding 2022-01-26 om 16 26 20" src="https://user-images.githubusercontent.com/3353713/151192939-0486ae34-f564-47fe-b99b-e126a110f5df.png">

### Steps to reproduce

Order and pay

<img width="1469" alt="Schermafbeelding 2022-01-26 om 16 24 03" src="https://user-images.githubusercontent.com/3353713/151192311-02630e77-731f-49f6-a4a6-1e27e76cdad7.png">

### Environment

Statamic 3.2.29 Solo
Laravel 8.78.1
PHP 7.4.13
cnj/seotamic 2.0.5
doublethreedigital/duplicator 2.1.0
doublethreedigital/simple-commerce 2.3.59
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
Which gateway are you using?

**Comment by studiovlijmscherp** [comment]
Mollie

**Comment by duncanmcclean** [comment]
What if you update Simple Commerce? I believe this has been fixed in a recent release.

**Comment by duncanmcclean** [comment]
This bug was fixed in [v2.3.60](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.60). You're currently on v2.3.59, if you update to the latest the issue should be fixed.

Let me know if you're still having issues after updating!
