### ISSUE TITLE
Error when applying coupon code

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#558]
### Bug Description

When applying a coupon code. The server returns an error 500.

Error log:
[laravel.log](https://github.com/doublethreedigital/simple-commerce/files/7992807/laravel.log)

My cart.antlers.html
[cart.antlers.html.zip](https://github.com/doublethreedigital/simple-commerce/files/7992814/cart.antlers.html.zip)

### Steps to reproduce

Add items to cart. Apply couponcode

### Environment

Statamic 3.2.29 Solo
Laravel 8.78.1
PHP 7.4.13
cnj/seotamic 2.0.5
doublethreedigital/duplicator 2.1.0
doublethreedigital/simple-commerce 2.3.64
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
What does your `cart.antlers.html` template look like?

**Comment by duncanmcclean** [comment]
Thanks! 

Looks like Statamic doesn't like augmenting fields called `value`. Since it would be a breaking change to change the field name & the fact it might be fixed at some point in Statamic Core, I've written a workaround. 

It should be fixed now for you, in v2.3.65. Have a great evening!

**Comment by studiovlijmscherp** [comment]
Updated to latest version. Get redirected to https://domain.com/!/simple-commerce/coupon 

with  another error:

419
PAGE EXPIRED

**Comment by duncanmcclean** [comment]
Oh, replace the CSRF bit you have with the 'csrf_field' tag.

I forgot to mention that haha. I also noticed you weren't using the tag but you're using a custom form?

**Comment by studiovlijmscherp** [comment]
Replace with what? 
Using a custom (ajax) form indeed.

**Comment by duncanmcclean** [comment]
Replace it with this: https://statamic.dev/variables/csrf_field

**Comment by studiovlijmscherp** [comment]
This doesn't solve the issue unfortunately. Still 419 Expired

`<form method="POST" action="/!/simple-commerce/coupon" class="flex flex-1">
                    {{ csrf_field }}
                    <input type="text" placeholder="Voer je kortingscode in" name="code" class="bg-transparent border border-brand-light p-3 rounded-l text-brand-light text-gray-800 text-lg flex-grow md:flex-grow-0">
                    <button type="submit" class="bg-brand-regular border border-brand-light hover:bg-brand-light hover:text-black p-3 rounded-r">`

**Comment by duncanmcclean** [comment]
That's odd, that fixed it for me when I tried. Are you using static caching?

**Comment by studiovlijmscherp** [comment]
Clearing the cache fixed it 👍🏻
