### ISSUE TITLE
Custom customer e-mail

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#568]
### What's the issue you're running into?

Hi. We would like to be able to customize the  e-mail customers are sent upon order completion.
Best would be load content from a CMS page and display this  as the e-mail body.

Read through the docs, but cannot seem to find any solution.

We're using the Mollie checkout. Somehow we're using the `site/resources/views/vendor/simple-commerce/order-confirmation.blade.php` now, but only for Mollie.

Tried ordering with the Dummy (card)  Gateway, this seems to be using some kind of default e-mail template.

Really puzzled here. Could use some help :-)

### Steps to reproduce

..

### Environment

Statamic 3.2.29 Solo
Laravel 8.78.1
PHP 7.4.27
cnj/seotamic 2.0.5
doublethreedigital/duplicator 2.1.0
doublethreedigital/simple-commerce 2.3.65
pecotamic/sitemap 1.2.7

**Comment by duncanmcclean** [comment]
You can do this by using a 'custom notification'. 

Essentially, you create a class that's pretty much a copy of the one in Simple Commerce. You'll need to change the `namespace` and update the Simple Commerce config. Then you can update the content in that class. 

If you need to make the content of the notification editable, I'd recommend using a global to store it, and you can retrieve it yourself using Statamic's [GlobalSet facade](https://statamic.dev/repositories/global-repository#querying).

I'm not entirely sure why the view you've mentioned is working. Maybe you already have a custom notification setup?

I'm happy to take a look at your repository if you're still stuck!

**Comment by duncanmcclean** [comment]
Closing this now as I've explained how to 'customise' Simple Commerce's emails in my previous comment. If you still need any help getting stuff setup, comment on here and I can re-open this issue.

Have a great weekend!

**Comment by studiovlijmscherp** [comment]
Hey! Still having issues configuring Customer Notifications. We're looking for a  way to send a simple notification email to customers. Preferably using  Blade.

We have a template (esources/views/vendor/simple-commerce/order-confirmation.blade.php) setup with these  contents:
```
Dear {{ $order['customer']->value()->data()->get('name') }}, <br>
<br>
Thanks for your order.<br>
<br>
Een smakelijke groet,
Team Beefs & Beers
www.beefsandbeers.com
```

All we would like to know  is how and where to place and use this template :-)
Hope you can  help!

**Comment by duncanmcclean** [comment]
You can use a custom notification class for the emails, which would allow you to use a Blade view for sending customer emails.

Various bits of docs that may be helpful:

* https://simple-commerce.duncanmcclean.com/notifications#content-using-a-custom-notification
* https://laravel.com/docs/9.x/notifications#other-mail-notification-formatting-options

Let me know if you have any other questions... at some point, I'll update the documentation to hopefully clear up the process of customising email notifications.
