### ISSUE TITLE
Add invoice to CustomerOrderPaid e-mail

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#569]
### What would you like to see added?

We would like to be able to attach the invoice PDF to the CustomerOrderPaid email

### Is there a workaround you can use in the meantime?

nope

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Are you talking about the email sent to the customer or to the back-office? It should already be attached on the email to the customer, see [notification code](https://github.com/doublethreedigital/simple-commerce/blob/2.3/src/Notifications/CustomerOrderPaid.php#L54).

**Comment by studiovlijmscherp** [comment]
We would like the invoice (which is sent to the customer) sent to the back-office too.

**Comment by duncanmcclean** [comment]
That's a fair point, I'll add the invoice to the back-office email this evening.
