### ISSUE TITLE
Customer title is not set correctly

### ISSUE THREAD

**Issue by steffenschmidt** [damcclean/simple-commerce#572]
### What's the issue you're running into?

When creating an order normally the customer title in my orders collection should be set by name and email address. Instead it is set to `simple-commerce::messages.customer_title`.

<img width="1237" alt="Screenshot 2022-02-21 at 09 33 16" src="https://user-images.githubusercontent.com/55256/154918678-295ad4a6-7cb6-4829-b22e-dc9ad7dc5969.png">

As I found that this is the language string I copied the `messages.php` from the `resources/lang/en` folder to my project to `resources/lang/de` but with the same behavior like mentioned before.

Not sure it belongs to the language setting. If I can get any help how to solve this issue.

Thanks

### Steps to reproduce

Not sure it belongs to the language setting but if it does you can do the following

* Set language to other than English
* Order something
* Check if customer title is set correctly in control panel

### Environment

Statamic 3.2.33 Pro
Laravel 8.83.1
PHP 8.1.0
aryehraber/statamic-logbook 2.0.2
doublethreedigital/simple-commerce 2.3.66
jackabox/statamic-plausible-analytics 1.1.0

**Comment by duncanmcclean** [comment]
What does your version of the `messages.php` file look like?

**Comment by steffenschmidt** [comment]
```
<?php

return [

    // …

    'customer_title'            => ':name <:email>',
    'product_has_no_variants'   => 'Keine Varianten.',
    'product_variants_singular' => 'Variante',
    'product_variants_plural'   => 'Varianten',

    // …
];

```

**Comment by duncanmcclean** [comment]
Thanks! I'll investigate once I'm finished at my day job.

**Comment by duncanmcclean** [comment]
That's odd, I don't seem to be able to reproduce this. I...

1. Created a language file with the contents from your above snippet: `resources/lang/de/messages.php`
2. Switched the `locale` in my `app.php` config to `de`
3. Ordered something
4. Saw that the customer title was correct in the CP

Is there anything I didn't do that I should be doing?

**Comment by duncanmcclean** [comment]
Closing this issue as I'm unable to reproduce it. 

If you can spot something I did wrong, let me know and I'll give it another shot (or even better, if you can make a fresh site where you can replicate the issue and share it 😄 ).

Have a great weekend!

**Comment by steffenschmidt** [comment]
So, I didn't found time before to dig deeper into it.

I changed my locale to English and tried these things out and it worked. So I would thing there is something wrong with my translation file.

English locale:
<img width="198" alt="Screenshot 2022-03-16 at 23 02 27" src="https://user-images.githubusercontent.com/55256/158698882-4ff92104-f114-4ce1-9c8f-da2d95f95942.png">

German locale:
<img width="312" alt="Screenshot 2022-03-16 at 23 02 56" src="https://user-images.githubusercontent.com/55256/158698893-d804645b-7404-4d19-befa-7593653299a4.png">

Same behavior with `simple-commerce::messages.customer_title`. 

What did I do?

1. I put your `messages.php` file from `/vendor/doublethreedigital/simple-commerce/resources/lang/en` and copied it to `/resources/lang/de`
2. I translated everything inside to work with the German language

What happened?

* No translation were shown, instead I see the translation strings

What else did I tried?

1. I cloned the en-folder in `/vendor/doublethreedigital/simple-commerce/resources/lang/` and renamed the clone to `de` so that I have both folders
2. I did not changed anything in the `/vendor/doublethreedigital/simple-commerce/resources/lang/de/messages.php` and it worked! Then it uses the translation file.

Could you give me a hint what I have to change in my language file? Do I have to add another structure level or something?

**Comment by duncanmcclean** [comment]
Please open a new issue.
