### ISSUE TITLE
Dependencies should be upgraded to support php 8.1

### ISSUE THREAD

**Issue by SimonJnsson** [damcclean/simple-commerce#575]
### What would you like to see added?

On `vendor/doublethreedigital/simple-commerce/src/Support/Currency.php:46` when attempting to create a Money instance for the item amount, an error occours 

`Return type of Money\Currency::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

This seems to be related to https://github.com/moneyphp/money/issues/656 and should be fixed in 4.0.3

In addition, running in php 8.1 will require a composer update for dependencies. Doing so results in a "DivisionByZeroError: Division by zero" error in \DoubleThreeDigital\SimpleCommerce\Tests\Http\Controllers\ReceiptControllerTest::can_show_receipt

### Steps to reproduce
Run php 8.1
composer update
composer test

### Is there a workaround you can use in the meantime?

Downgrade to php 8.0

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Just tagged a fix for this which will be out in a few minutes. I've fixed both the MoneyPHP issue and the 'Division by zero' issue on the receipt.

For some reason, even using PHP 8.1, I could only reproduce the receipt issue but I've (hopefully) fixed both anyways.
