### ISSUE TITLE
Order is created every time there is an intent but no payment

### ISSUE THREAD

**Issue by lokmanm** [damcclean/simple-commerce#578]
### Bug Description

Hi Duncan,

I was not sure if this is a bug or feature but If you add a product to the cart go to checkout and remove the product it will show up as a new order with intent. 

This can easily pollute the orders collection every time someone is trying to add a product and then remove it.

### Steps to reproduce

1. Add a product to cart
2. Go to checkout
3. Remove product
4. Check orders collection

### Environment

```
Statamic 3.2.32 Pro
Laravel 7.30.6
PHP 8.0.14
aryehraber/statamic-captcha 1.7.0
doublethreedigital/sc-digital-products 2.2.3
doublethreedigital/simple-commerce 2.3.64
doublethreedigital/yumyum 1.1.0
statamic/seo-pro 2.3.2
```

**Comment by duncanmcclean** [comment]
Correct, that's the intended behaviour. If you don't want to keep unpaid orders, you can delete them with a schuduled task (or something similar). 

Simple Commerce *should* be automatically filtering the orders in the CP to paid orders only so you don't see a bunch of junk orders. 

<img width="748" alt="image" src="https://user-images.githubusercontent.com/19637309/155422013-5fb1233a-8d77-4985-b6cf-c8c81ca1a2db.png">
