### ISSUE TITLE
How to run validations before PayPal onsite checkout?

### ISSUE THREAD

**Issue by steffenschmidt** [damcclean/simple-commerce#584]
### What's the issue you're running into?

I am using PayPalGateway with onsite mode for payments. In my last step I added a checkbox to accept terms and conditions for my order. As I am using the PayPal onsite method the validation is run after I return from PayPal so the payment is done although the checkbox isn't accepted.

```html
{{ sc:checkout id="checkout-form" request="CheckoutPaymentRequest" redirect="/checkout/complete" }}

<p>
  <label for="AcceptedTermsAndConditionsCheckbox">
    <input type="checkbox" name="accepted_terms_and_conditions" value="1" id="AcceptedTermsAndConditionsCheckbox">
    Ich akzeptiere die <a href="/agb" target="_blank">allgemeinen Geschäftsbedingungen</a>.
  </label>
</p>

{{ sc:gateways }}
  {{ partial src="checkout/gateways/paypal" }}
{{ /sc:gateways }}

{{ /sc:checkout }}
```

My CheckoutPaymentRequest class is the following:

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CheckoutPaymentRequest extends FormRequest
{
  /**
   * Get the validation rules that apply to the request.
   *
   * @return array
   */
  public function rules()
  {
    return [
      'accepted_terms_and_conditions' => 'accepted',
    ];
  }

  /**
   * Get the error messages for the defined validation rules.
   *
   * @return array
   */
  public function messages()
  {
    return [
      'accepted_terms_and_conditions.accepted' => 'Bitte bestätige, dass du die Allgemeinen Geschäftsbedingungen akzeptierst.',
    ];
  }
}
```

As written before the validation is done after returning back from PayPal. How can I make sure that the validation is done before?

### Steps to reproduce

See above.

### Environment

Statamic 3.2.35 Pro
Laravel 8.83.3
PHP 8.1.0
aryehraber/statamic-logbook 2.0.2
doublethreedigital/simple-commerce 2.3.69
jackabox/statamic-plausible-analytics 1.1.0

**Comment by duncanmcclean** [comment]
Sorry, would you be able to record a quick screencast of what the checkout flow looks like when using PayPal as an on-site gateway.

I can't quite remember how it works in on-site mode & I don't have a PayPal account handy to test with.

Thanks!

**Comment by steffenschmidt** [comment]
Of course. Here you find a 30s screencast. I hope the German part in the screencast is not a problem for understanding.

https://user-images.githubusercontent.com/55256/156844482-bf63703e-d5e7-43ec-9fa5-e0c4964d956d.mp4

Hopefully it helps otherwise let me know how I can support.

**Comment by duncanmcclean** [comment]
Thanks - that's really helpful! 

I'm not sure if Simple Commerce can really fix this problem since opening up the PayPal checkout is done on the front-end & the checkbox is only validated when you submit the `{{ sc:checkout }}` form which I don't _believe_ is actually happening in this case.

You might be best doing some kind of validation in your JavaScript if possible to fix this problem? Something like: if paypal button clicked, check checkbox value - if it's not checked, show an error to the user, otherwise continue to PayPal checkout.

**Comment by duncanmcclean** [comment]
For context: I didn't build out the PayPal on-site mode, it was contributed by a fellow customer so I could be slightly wrong about how it all fits together. Sorry in advance if that's the case! 😅

**Comment by steffenschmidt** [comment]
Good point to do the validation on client side. I will try this.

I also thought about adding another step in the checkout process to handling the validation before going the PayPal way.

Thanks for your help und hint.
