### ISSUE TITLE
Notifications not sending

### ISSUE THREAD

**Issue by lenartpapez** [damcclean/simple-commerce#586]
### What's the issue you're running into?

I have been trying to get notifiables to work with Mailtrap for testing purposes. This is in my config. I am using Mollie gateway, which is working perfectly. I have also tried to use `post_checkout` instead of `order_paid` but to no success.
```
'notifications' => [
        'order_paid' => [
            \App\Notifications\OrderPaidNotification::class => ['to' => 'customer']
        ],
 ],
```

Mailtrap .env variables are 100% set correctly. Might I mention I had to override the Cart and CartItem controllers to support some minor custom features. Do you think this could have anything to do with it? 

In CartController update method I am just concatenating name and surname form fields into the name field for the customer, as a client wanted to have those fields separate in the FE form. Everything else stays like the original.

In CartItem controller store method I just clear the cart when a new item is added as I wanted to support max 1 item per cart. Specific demands.

I don't think this has anything to do with the broken notifiable behaviour but I thought I'd mention it anyway.

### Steps to reproduce

1. Add a product to cart
2. Checkout with Mollie Gateway
3. Observe the mailtrap client (no notifications recieved)

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.0
PHP 8.0.11
doublethreedigital/simple-commerce 2.3.69
spatie/statamic-responsive-images 2.8.5

**Comment by duncanmcclean** [comment]
Thanks! I'll take a look this evening after I've finished my day job.

**Comment by duncanmcclean** [comment]
Just a quick question: you're talking about in the CartController update and the CartItemController, are you customising them?

**Comment by lenartpapez** [comment]
> Just a quick question: you're talking about in the CartController update and the CartItemController, are you customising them?

Yes. I've copied both controllers into App\Http\Controllers and then in the AppServiceProvider I am binding your package controllers to my own controllers so the routes use my own controllers instead.

**Comment by duncanmcclean** [comment]
Okay - I'll see if I can reproduce later on but I'd warn against binding your own controllers in case there's changes in SC's version which could conflict/cause issues for you.

**Comment by duncanmcclean** [comment]
Just looked into this and unfortunately I can't replicate. The notifications pull through fine. 

A couple of things for you to check to check:

* Are you running something like Expose/Ngrok for the webhook to use?
* If you view the payment in Mollie, are there any errors in the 'History' timeline?
* Does the order end up getting marked as paid?

**Comment by lenartpapez** [comment]
> Just looked into this and unfortunately I can't replicate. The notifications pull through fine.
> 
> A couple of things for you to check to check:
> 
> * Are you running something like Expose/Ngrok for the webhook to use?
> * If you view the payment in Mollie, are there any errors in the 'History' timeline?
> * Does the order end up getting marked as paid?

Hm, interesting.

1. Worth mentioning - this is already on a Digital Ocean server, running on Laravel Forge. So no, no Expose/Ngrok for the webhook.
2. Interestingly, yes. There is one error in the history, although the payment still comes as successful/paid. [See here](https://prnt.sc/WqkWAaSb-vkr)
4. Yes, the order is marked as paid both in Mollie and in Control Panel.

**Comment by duncanmcclean** [comment]
Ah, there will be something in your logs to align with the 500 error Mollie got. If you try again, then can you paste the last error from your `storage/logs/laravel.log` file?

**Comment by lenartpapez** [comment]
[Here](https://pastebin.com/ggerbfkG) seems like the 'customer' parameter is not being recognized correctly?

**Comment by lenartpapez** [comment]
> [Here](https://pastebin.com/ggerbfkG) seems like the 'customer' parameter is not being recognized correctly?

A quick google search suggested that I removed these two parameters from the .env file:
- MAIL_FROM_ADDRESS=null
- MAIL_FROM_NAME="${APP_NAME}"

I can confirm that after removing these lines the notifications are coming through. Wow, what a ride. I've tried literally everything before.

**Comment by duncanmcclean** [comment]
You can keep those, you just need to set a from address or you'll get that error:

```
MAIL_FROM_ADDRESS=noreply@example.com
MAIL_FROM_NAME="${APP_NAME}"
```
