### ISSUE TITLE
Translations from language file were not shown

### ISSUE THREAD

**Issue by steffenschmidt** [damcclean/simple-commerce#587]
### What's the issue you're running into?

So, I didn't found time before to dig deeper into my language problem of #572.

I changed my locale to English and tried these things out and it worked. So I would thing there is something wrong with my translation file.

English locale:
<img width="198" alt="Screenshot 2022-03-16 at 23 02 27" src="https://user-images.githubusercontent.com/55256/158698882-4ff92104-f114-4ce1-9c8f-da2d95f95942.png">

German locale:
<img width="312" alt="Screenshot 2022-03-16 at 23 02 56" src="https://user-images.githubusercontent.com/55256/158698893-d804645b-7404-4d19-befa-7593653299a4.png">

Same behavior with `simple-commerce::messages.customer_title`. 

What did I do?

1. I put your `messages.php` file from `/vendor/doublethreedigital/simple-commerce/resources/lang/en` and copied it to `/resources/lang/de`
2. I translated everything inside to work with the German language

What happened?

* No translation were shown, instead I see the translation strings

What else did I tried?

1. I cloned the en-folder in `/vendor/doublethreedigital/simple-commerce/resources/lang/` and renamed the clone to `de` so that I have both folders
2. I did not changed anything in the `/vendor/doublethreedigital/simple-commerce/resources/lang/de/messages.php` and it worked! Then it uses the translation file.

Could you give me a hint what I have to change in my language file? Do I have to add another structure level or something?

### Steps to reproduce

Not sure it belongs to the language setting but if it does you can do the following

* Set language to other than English
* Check if translations are shown correctly in control panel

My language file looks like the following:

```php
<?php

return [

    'actions' => [
        'mark_as_paid' => 'Als bezahlt markieren',
        'refund' => 'Rückerstattung',
    ],

    // …
];
```

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 8.1.0
aryehraber/statamic-logbook 2.0.2
doublethreedigital/simple-commerce 2.3.69
jackabox/statamic-plausible-analytics 1.1.0

**Comment by duncanmcclean** [comment]
Thanks, I'll take a look tomorrow evening and see if I can replicate.

**Comment by duncanmcclean** [comment]
Just taken a look into this & they seem to be pulling through fine for me:

![image](https://user-images.githubusercontent.com/19637309/158867885-72a060d5-24b3-44a7-b28a-049a8a5d7aa2.png)

One thing that's worth noting is that any Simple Commerce translations should live in `resources/lang/vendor/simple-commerce/de`.

![image](https://user-images.githubusercontent.com/19637309/158868046-aebb400b-63df-4b57-85a4-85d080fec81c.png)

**Comment by steffenschmidt** [comment]
Thanks for that hint, that directory structure solved everything!
