### ISSUE TITLE
Getting line item total including tax?

### ISSUE THREAD

**Issue by allmarkedup** [damcclean/simple-commerce#602]
### What's the issue you're running into?

Hello :) I'm just evaluating Simple Commerce and am really enjoying it so far. But I have a question about line item totals.

I'm using the new standard tax engine and have set up my tax rates, with a default address, and checked the 'include in price' option. It all works very nicely, except when looping over line items in my cart, the line item `{{ total }}` value doesn't include the tax, which looks a bit odd:

<img width="444" alt="Screenshot 2022-04-05 at 08 20 38" src="https://user-images.githubusercontent.com/126726/161700821-99050e22-c3d1-4a2a-aae8-ea8b2e3b75d0.png">

Is there any way to get the total for each line item **including** the tax amount? I've looked in the docs but can't seem to find anything - apologies if I've missed it somewhere!

Any help would be greatly appreciated.

### Steps to reproduce

* Set up the standard tax engine with default address
* Add a tax rate with 'included in price' option checked
* Render cart line items as described in the docs

### Environment

Statamic 3.3.4 Solo
Laravel 8.83.2
PHP 8.1.3
doublethreedigital/simple-commerce 2.4.8

**Comment by duncanmcclean** [comment]
I'll have a look now and see what I can do 😅

**Comment by duncanmcclean** [comment]
Just tagged a release (v2.4.9) which will include a tag to let you do this. Update to the release, then do `{{ total_including_tax }}` and you should be good to go!

Have a great rest of your day!

**Comment by allmarkedup** [comment]
@duncanmcclean Really appreciate the quick turnaround on getting an update out to sort this out! Many thanks, I'll download the update now. Have a good eve yourself :-)

**Comment by de-raaf-media** [comment]
Should this still work in v6? I get an error when using {{ total_including_tax }} "Call to a member function raw() on int"

In the Tag is can confirm that in total total is an integer. $total = $this->context->get('total')->raw(). The price of this specific product is 10.00.

{{ tax:amount }} does seem to work for showing the tax only.

**Comment by duncanmcclean** [comment]
> Should this still work in v6? I get an error when using {{ total_including_tax }} "Call to a member function raw() on int"

Yes, it should still work in v6. If you're experiencing an issue with it, please open a new issue.
