### ISSUE TITLE
Stripe unable to refund via CP

### ISSUE THREAD

**Issue by drewtoma** [damcclean/simple-commerce#624]
### Bug Description

I'm unable to refund a stripe order via the CP

### Steps to reproduce

Enter the CP and click the three dots and hit refund

### Environment

[2022-04-26 18:56:06] production.ERROR: Stripe: No Payment Intent was provided to action a refund. {"userId":"b0a6033d-896f-41ba-a3e1-921b60fe7a1b","exception":"[object] (DoubleThreeDigital\\SimpleCommerce\\Exceptions\\RefundFailed(code: 0): Stripe: No Payment Intent was provided to action a refund. at /home/forge/[lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/StripeGateway.php:137](http://lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/StripeGateway.php:137))
[stacktrace]
#0 /home/forge/[lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Gateways/Manager.php](http://lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Gateways/Manager.php)(72): DoubleThreeDigital\\SimpleCommerce\\Gateways\\Builtin\\StripeGateway->refundCharge()
#1 /home/forge/[lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Actions/RefundAction.php](http://lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Actions/RefundAction.php)(45): DoubleThreeDigital\\SimpleCommerce\\Gateways\\Manager->refundCharge()
#2 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php)(263): DoubleThreeDigital\\SimpleCommerce\\Actions\\RefundAction->DoubleThreeDigital\\SimpleCommerce\\Actions\\{closure}()
#3 /home/forge/[lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Actions/RefundAction.php](http://lifesafety.org/vendor/doublethreedigital/simple-commerce/src/Actions/RefundAction.php)(46): Illuminate\\Support\\Collection->each()
#4 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Controllers/CP/ActionController.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Controllers/CP/ActionController.php)(36): DoubleThreeDigital\\SimpleCommerce\\Actions\\RefundAction->run()
#5 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Controller.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Controller.php)(54): Statamic\\Http\\Controllers\\CP\\ActionController->run()
#6 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php)(45): Illuminate\\Routing\\Controller->callAction()
#7 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php)(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php)(204): Illuminate\\Routing\\Route->runController()
#9 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php)(725): Illuminate\\Routing\\Route->run()
#10 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /home/forge/[lifesafety.org/vendor/kind-work/two-fa/src/Middleware/CheckTwoFa.php](http://lifesafety.org/vendor/kind-work/two-fa/src/Middleware/CheckTwoFa.php)(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): KindWork\\TwoFa\\Middleware\\CheckTwoFa->handle()
#13 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php)(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#15 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php)(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#17 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php)(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#19 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php)(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle()
#21 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php)(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle()
#23 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php)(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#25 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php)(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php)(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php)(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php)(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php)(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php)(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php)(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php)(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#40 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php)(726): Illuminate\\Pipeline\\Pipeline->then()
#42 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php)(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#43 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php)(667): Illuminate\\Routing\\Router->runRoute()
#44 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php)(656): Illuminate\\Routing\\Router->dispatchToRoute()
#45 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php)(167): Illuminate\\Routing\\Router->dispatch()
#46 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#47 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php)(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#49 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php)(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#51 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php)(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#53 /home/forge/[lifesafety.org/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php](http://lifesafety.org/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php)(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#55 /home/forge/[lifesafety.org/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php](http://lifesafety.org/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php)(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#57 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php)(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php)(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#60 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php)(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php)(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#62 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#63 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php)(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#65 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php)(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#67 /home/forge/[lifesafety.org/vendor/fruitcake/laravel-cors/src/HandleCors.php](http://lifesafety.org/vendor/fruitcake/laravel-cors/src/HandleCors.php)(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Fruitcake\\Cors\\HandleCors->handle()
#69 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php)(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#71 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php)(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php)(142): Illuminate\\Pipeline\\Pipeline->then()
#73 /home/forge/[lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php](http://lifesafety.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php)(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#74 /home/forge/[lifesafety.org/public/index.php](http://lifesafety.org/public/index.php)(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#75 {main}
“}

**Comment by duncanmcclean** [comment]
Although this has now been fixed, it'll only fix the issue for future orders, not past orders. If you need to refund a past order, I'd recommend doing so within the Stripe Dashboard.
