### ISSUE TITLE
Component gateway-fieldtype does not exist.

### ISSUE THREAD

**Issue by drewtoma** [damcclean/simple-commerce#628]
### Bug Description

Gateway
Read Only
Component gateway-fieldtype does not exist.

### Steps to reproduce

Upgrade from previous version. Open new order.

### Environment

Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.1.4
aryehraber/statamic-uuid 2.1.0
doublethreedigital/simple-commerce 3.0.1
edalzell/forma 1.1
kind-work/two-fa 1.5.1
rias/statamic-address-field 1.0.2
rias/statamic-redirect 2.2.0
silentz/akismet 3.1.1
silentz/mailchimp 2.9
statamic/seo-pro 3.1.0

**Comment by duncanmcclean** [comment]
Where are you getting this error? When you open up an order? In the console? Can you share your order blueprint?

**Comment by drewtoma** [comment]
Here is my reservations(order) blueprint:

title: Reservations
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: false
          validate:
            - required
      -
        handle: is_paid
        field:
          type: toggle
          listable: false
          display: 'Is Paid?'
          width: 50
          read_only: true
      -
        handle: customer
        field:
          max_items: 1
          mode: default
          collections:
            - students
          type: entries
          listable: hidden
          display: Student
          width: 50
          read_only: true
          instructions_position: above
          create: true
      -
        handle: coupon
        field:
          max_items: 1
          mode: select
          collections:
            - coupons
          type: entries
          listable: false
          display: Coupon
          width: 50
          read_only: true
          instructions_position: above
          create: true
      -
        handle: items
        field:
          fields:
            -
              handle: id
              field:
                type: hidden
                listable: hidden
                display: ID
            -
              handle: product
              field:
                max_items: 1
                mode: default
                collections:
                  - schedule
                type: entries
                listable: hidden
                display: Class
                validate: required
                width: 50
                read_only: true
                instructions_position: above
                create: true
            -
              handle: variant
              field:
                display: Variant
                type: product_variant
                icon: product_variant
                width: 50
                listable: hidden
                read_only: true
            -
              handle: quantity
              field:
                input_type: number
                type: text
                listable: hidden
                display: Quantity
                width: 50
                read_only: true
            -
              handle: total
              field:
                type: money
                listable: hidden
                display: Total
                validate: required
                width: 50
                read_only: true
            -
              handle: metadata
              field:
                mode: dynamic
                display: Metadata
                type: array
                icon: array
                listable: hidden
                read_only: true
            -
              handle: tax
              field:
                type: sc_line_items_tax
          mode: stacked
          reorderable: false
          type: grid
          listable: false
          display: 'Line Items'
          min_rows: 1
          add_row: 'Add Class'
          instructions_position: above
          read_only: false
      -
        handle: learn_about
        field:
          antlers: false
          display: 'How did you learn about us?'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          read_only: true
      -
        handle: shirt_size
        field:
          input_type: text
          antlers: false
          display: 'Shirt Size'
          type: text
          icon: text
          instructions: 'What''s your shirt size? (Mens/Woman''s - XS/S/M/L/XL/XXL/XXL)'
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: date_of_birth
        field:
          mode: single
          time_enabled: false
          time_seconds_enabled: false
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Date of Birth'
          type: date
          icon: date
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: phone_number
        field:
          input_type: text
          antlers: false
          display: 'Phone Number'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
  addresses:
    display: Addresses
    fields:
      -
        handle: section
        field:
          type: section
          listable: false
          display: Address
          instructions_position: above
          read_only: false
      -
        handle: address_1
        field:
          input_type: text
          type: text
          listable: false
          display: 'Address 1'
          width: 50
          antlers: false
          read_only: true
          instructions_position: above
      -
        handle: address_2
        field:
          input_type: text
          antlers: false
          display: 'Address 2'
          type: text
          icon: text
          width: 50
          listable: hidden
          read_only: true
          instructions_position: above
      -
        handle: city
        field:
          input_type: text
          type: text
          listable: false
          display: City
          width: 50
          read_only: true
          instructions_position: above
          antlers: false
      -
        handle: zip
        field:
          input_type: text
          type: text
          width: 50
          listable: false
          display: 'Zip Code'
          read_only: true
          instructions_position: above
          antlers: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: hidden
          localizable: true
          display: Slug
          icon: hidden
          listable: false
          validate:
            - required
          read_only: true
      -
        handle: paid_date
        field:
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          listable: hidden
          display: 'Paid Date'
          validate: required
          read_only: true
          instructions_position: above
          time_seconds_enabled: false
      -
        handle: items_total
        field:
          type: money
          display: 'Items Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
      -
        handle: coupon_total
        field:
          type: money
          display: 'Coupon Total'
          read_only: true
          validate: required
          width: 33
          listable: false
      -
        handle: tax_total
        field:
          type: money
          display: 'Tax Total'
          read_only: true
          validate: required
          width: 33
          listable: false
      -
        handle: shipping_total
        field:
          type: money
          display: 'Shipping Total'
          read_only: true
          validate: required
          width: 33
          listable: false
      -
        handle: grand_total
        field:
          type: money
          display: 'Grand Total'
          read_only: true
          validate: required
          width: 33
          listable: hidden
      -
        handle: gateway
        field:
          display: Gateway
          type: gateway
          read_only: true
      -
        handle: shipping_method
        field:
          display: 'Shipping Method'
          type: shipping_method
          read_only: true
      -
        handle: order_number
        field:
          type: hidden



From: Duncan McClean ***@***.***>
Reply-To: doublethreedigital/simple-commerce ***@***.***>
Date: Thursday, May 12, 2022 at 11:46
To: doublethreedigital/simple-commerce ***@***.***>
Cc: Drew Toma ***@***.***>, Author ***@***.***>
Subject: Re: [doublethreedigital/simple-commerce] Component gateway-fieldtype does not exist. (Issue #628)


Where are you getting this error? When you open up an order? In the console? Can you share your order blueprint?

**Comment by duncanmcclean** [comment]
Does it work if you run `php artisan statamic:install` and do a hard refresh in your browser?

**Comment by drewtoma** [comment]
Yes, that fixed it!

From: Duncan McClean ***@***.***>
Reply-To: doublethreedigital/simple-commerce ***@***.***>
Date: Thursday, May 12, 2022 at 11:52
To: doublethreedigital/simple-commerce ***@***.***>
Cc: Drew Toma ***@***.***>, Author ***@***.***>
Subject: Re: [doublethreedigital/simple-commerce] Component gateway-fieldtype does not exist. (Issue #628)


Does it work if you run php artisan statamic:install and do a hard refresh in your browser?
