### ISSUE TITLE
php please sc:cart-cleanup Not Working

### ISSUE THREAD

**Issue by drewtoma** [damcclean/simple-commerce#631]
### Bug Description

After updating the following error is given:

% php please sc:cart
Cleaning up..

   Error

  Call to undefined method DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository::query()

  at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:337
    333▕         if (! $instance) {
    334▕             throw new RuntimeException('A facade root has not been set.');
    335▕         }
    336▕
  ➜ 337▕         return $instance->$method(...$args);
    338▕     }
    339▕ }
    340▕

      +14 vendor frames
  15  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

### Steps to reproduce

php please sc:cart-cleanup

### Environment

Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.1.4
aryehraber/statamic-uuid 2.1.0
doublethreedigital/simple-commerce 3.0.2
edalzell/forma 1.1
kind-work/two-fa 1.5.1
rias/statamic-address-field 1.0.2
rias/statamic-redirect 2.2.0
silentz/akismet 3.1.1
silentz/mailchimp 2.9
statamic/seo-pro 3.1.0

**Comment by duncanmcclean** [comment]
Confirmed - I'll take a this evening.
