### ISSUE TITLE
Order number in email and receipt always different to the one in CP

### ISSUE THREAD

**Issue by lenartpapez** [damcclean/simple-commerce#632]
### What's the issue you're running into?

I've been looking tirelessly if there is something wrong with my code but I can't seem to find the issue. Everything is going well but one thing;

- Order number in CP is for example: 1029
- Order number for the order_paid notification email and receipt is 1027

I am using the latest CustomerOrderPaid notification class. 

Any ideas as to where/why this might be happening?

### Steps to reproduce

I can give you access to the remote repository where this project is located. Just say the words.

### Environment

Statamic 3.3.11 Pro
Laravel 8.83.12
PHP 8.0.11
doublethreedigital/simple-commerce 3.0.3
spatie/statamic-responsive-images 2.11.2

**Comment by duncanmcclean** [comment]
I'm guessing you're storing your orders as entries, yeah? Are both orders marked as paid in the CP - it should just be one of them?

Having access to the code would certainly be the easiest way to look into it - I'm `duncanmcclean` on GitHub or if it's elsewhere, add `duncan@doublethree.digital`.

**Comment by lenartpapez** [comment]
Yeah, as an entry. This is the same order, mind you. I only have one order in the collections view. The problem is that the order number differs when view in CP versus the number in the email/receipt. It's weird.

I added you as a collaborator.  I'll email you with further instructions to reproduce.

**Comment by duncanmcclean** [comment]
Thanks - I'll take a look tonight!

**Comment by duncanmcclean** [comment]
Thanks for inviting me to the repository! I managed to reproduce the bug and have tagged a release which will be out shortly/now.

Have a great evening!
