### ISSUE TITLE
V3.0.4 shipping_zip_code not migrated to shipping_postal_code

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#633]
### Bug Description

In our V2.* setup we have been using shipping_zip_code to store the customers zip codes.

In V3.0.* this fields seems to be replaced by shipping_postal_code. Upon the migration to the database it doesn't take this into account when migrating the data. This way this information is missing from the order table.

### Steps to reproduce

Migrate a site from V.2.*, including a set of orders, to V3.0*.

### Environment

Statamic 3.3.12 Pro
Laravel 8.83.13
PHP 8.0.19
doublethreedigital/runway 2.3.5
doublethreedigital/simple-commerce 3.0.4
joetannenbaum/antlers-stack-tags 0.1.0
optimoapps/statamic-bard-text-align 1.0.2
roorda-ict/statamic-entries-export 1.0.0

**Comment by duncanmcclean** [comment]
Actually, we should probably let you keep the original key/column name so you don't have to update references everywhere, you'd just need to update your migration.

Closing in favour of #634 (as it'll handle that).
