### ISSUE TITLE
Order tag doesn't work

### ISSUE THREAD

**Issue by tevarjohnson** [damcclean/simple-commerce#641]
### Bug Description

This below works

```
{{ sc:customer id="{ current_user:id }" }}

  Your name is {{ first_name }} {{ last_name }} and your email is {{ email }}

{{ /sc:customer }}
```

This doesn't works
```
{{ sc:customer:orders customer="{ current_user:id }" }}
  {{ title }} - {{ grand_total }}
{{ /sc:customer:orders }}
```

it returns
`Method Statamic\Tags\Parameters::customer does not exist.`

### Steps to reproduce

1. Installed the code, 2. made customers users 3. made purchases 4. tried to use the supply tag to load purchases using the user id.

### Environment

Statamic 3.3.12 Pro
Laravel 9.14.1
PHP 8.1.6
doublethreedigital/duplicator 2.2.0
doublethreedigital/sc-digital-products 3.1.0
doublethreedigital/simple-commerce 3.0.4
jacksleight/statamic-memberbox 0.5.1

**Comment by duncanmcclean** [comment]
Fixed in latest release.
