### ISSUE TITLE
Order query not returning results

### ISSUE THREAD

**Issue by tevarjohnson** [damcclean/simple-commerce#645]
### Bug Description

I used the supplied query to return orders from a user but it doesnt return any.

### Steps to reproduce

Clone repo https://gitlab.com/tevar/district. make an account, place a order then go to /dashboard

### Environment

Statamic 3.3.13 Pro
Laravel 9.16.0
PHP 8.1.6
doublethreedigital/duplicator 2.2.0
doublethreedigital/sc-digital-products 3.2.1
doublethreedigital/simple-commerce 3.2.3
jacksleight/statamic-memberbox 0.5.1

**Comment by duncanmcclean** [comment]
Thanks for providing the repo! This should now be fixed for you:

1. Update Simple Commerce
2. Also, I noticed you had the customer ID wrong and the grand total wasn't pulling through. You probably want to update them to be something like this:

```antlers
{{ sc:customer:orders customer="{ current_user:id }" }}
  order title: {{ title }} - price: {{ grand_total }}
{{ /sc:customer:orders }}
```

If you run into any other issues, please open a GitHub issue and I can take a look into them.
