### ISSUE TITLE
Coupon calculations incorrect

### ISSUE THREAD

**Issue by mscruse** [damcclean/simple-commerce#651]
### Bug Description

I am experiencing an issue with the calculation of coupon discounts. I have created 2 coupons:

Coupon 1 - Fixed Discount. I create a $10 discount and enter 10.00 in the value field of the coupon. When I go to use this coupon it gives a discount of $0.10 (10 cents). If I enter 1000 in the value field I get the $10 discount.

Coupon 2 - Percentage Discount. I create a 10% discount and there 10 as the value. When using this coupon it multiplies the order items total by 10. NOTE this only seems to happen when the price of an item is not a whole dollar, e.g. $24.99. If it is $25.00 then it works OK.

<note: this SC project has been in development for about a year so it has been upgraded along the way but started on a 2.x install of SC>

### Steps to reproduce

Create the coupons as above and test.

### Environment

Statamic 3.3.13 Pro
Laravel 9.17.0
PHP 8.1.5
aryehraber/statamic-captcha 1.8.0
aryehraber/statamic-font-awesome 2.2.0
doublethreedigital/duplicator 2.2.0
doublethreedigital/simple-commerce 3.2.6
mitydigital/simple-commerce-australia-post 1.0.0
rias/statamic-redirect 2.3.5
statamic/seo-pro 3.1.0

**Comment by duncanmcclean** [comment]
Thanks for this issue - I don't have any time to look into it tonight but will try and take a look tomorrow 👍

**Comment by duncanmcclean** [comment]
Note to self: re-watch video recording sent over via email
