### ISSUE TITLE
CP Order list missing field values

### ISSUE THREAD

**Issue by mscruse** [damcclean/simple-commerce#652]
### Bug Description

When viewing orders in the CP the Title field is blank (so nothing to click to view the order) and the Customer name is not shown.

<img width="1703" alt="Screen Shot 2022-06-08 at 11 23 26 am" src="https://user-images.githubusercontent.com/22737928/172513906-c70bc3c8-072b-43b7-ad56-89e1e37861bd.png">

The same when you edit the order.

<img width="1147" alt="Screen Shot 2022-06-08 at 11 48 04 am" src="https://user-images.githubusercontent.com/22737928/172513977-c84c7fd0-0c77-40fb-ba6f-42a00be4ce4c.png">

I have compared my blueprint fields to a fresh Statamic / SC install and they look the same.

### Steps to reproduce

View orders in CP

### Environment

Statamic 3.3.13 Pro
Laravel 9.17.0
PHP 8.1.5
aryehraber/statamic-captcha 1.8.0
aryehraber/statamic-font-awesome 2.2.0
doublethreedigital/duplicator 2.2.0
doublethreedigital/simple-commerce 3.2.6
mitydigital/simple-commerce-australia-post 1.0.0
rias/statamic-redirect 2.3.5
statamic/seo-pro 3.1.0

**Comment by duncanmcclean** [comment]
If you go into edit the collection’s settings - is there a title format configured?

**Comment by mscruse** [comment]
It didn't so I added as per my test new install, but it's still not showing in the orders list view.

**Comment by duncanmcclean** [comment]
I think only new orders will use the title format - does it work if you make a new order?

**Comment by duncanmcclean** [comment]
Also (you may have already mentioned this but I'm in a rush to finish for the day), can you replicate this on a fresh starter kit site?

**Comment by duncanmcclean** [comment]
Just given this a test myself on a fresh site created from the starter kit and the order title seems to have pulled through correctly.

![image](https://user-images.githubusercontent.com/19637309/172924235-7fc76cd2-46b0-4580-98c9-e2b17d55bf35.png)

When you upgraded to v3, the title formats for customers & orders should have been setup for you automatically. If not, set them to these in your collection settings:

* Customers: `'{name} <{email}>'`
* Orders: `'#{order_number}'`

After you have them configured, try creating a fresh order and see if starts to work then?

Hopefully that'll help 👍

**Comment by mscruse** [comment]
Thanks Duncan - this fixed it. I really appreciate your help.

**Comment by studiovlijmscherp** [comment]
We're having  the same  issue. Where /how do we need  to edit these settings?

**Comment by duncanmcclean** [comment]
> We're having the same issue. Where /how do we need to edit these settings?

In the settings for each of the collections.

**Comment by studiovlijmscherp** [comment]
Seems my issue is somewhat different. I've recently upgraded to 2.4.11.
Missing quite some fields in the blueprints (like the hidden field for the order number). Also; my orders.yaml is called aorder.yaml (site/resources/blueprints/collections/orders/order.yaml). Looks like the upgrade did't update all the files. Could  use some help.

**Comment by duncanmcclean** [comment]
> Seems my issue is somewhat different. I've recently upgraded to 2.4.11. Missing quite some fields in the blueprints (like the hidden field for the order number). Also; my orders.yaml is called aorder.yaml (site/resources/blueprints/collections/orders/order.yaml). Looks like the upgrade did't update all the files. Could use some help.

This might be better in it's own issue - would you be able to create one? Otherwise, Michael will keep getting notified 😅
