### ISSUE TITLE
Change order status via cp

### ISSUE THREAD

**Issue by barchard** [damcclean/simple-commerce#654]
### What would you like to see added?

It would be nice to be able to change an order status (paid, unpaid or refunded) via the cp

### Is there a workaround you can use in the meantime?

I don't know. Maybe manually editing the file on disk?

### Priority wise - where's this feature for you?

Nice to have

**Comment by duncanmcclean** [comment]
Orders should only be able to be marked paid by checking-out. And otherwise, refunds and setting an order as shipped can already be achieved in the CP.
