### ISSUE TITLE
The Remove Product link doesn't remove a product from the cart

### ISSUE THREAD

**Issue by qbixx** [damcclean/simple-commerce#665]
### Bug Description

I've added the `{{ sc:cart:removeItem :item="id" }}` tag to make it possible to delete products from the cart. However when the user clicks the link, nothing happens.

I'm using `{{ sc:cart }}` to open the form and the following code for the remove button:

```
{{ sc:cart:removeItem :item="id" }}
<button type="button" class="-m-2 p-2 inline-flex text-gray-400 hover:text-gray-500">
<span class="sr-only">Remove</span>
<!-- Heroicon name: solid/x -->
<svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
</svg>
</button>
{{ /sc:cart:removeItem }}
```

### Steps to reproduce

1. Add the code to the cart.antlers.html file
2. Add a product to the cart
3. Try to remove the product

### Environment

Statamic 3.3.15 Pro
Laravel 9.17.0
PHP 8.0.20
doublethreedigital/simple-commerce 3.2.6

**Comment by duncanmcclean** [comment]
What if you change `type="button"` to `type="submit"`?

**Comment by qbixx** [comment]
Changing the button to a submit button works! Thanks!
