### ISSUE TITLE
419 Page expired

### ISSUE THREAD

**Issue by qbixx** [damcclean/simple-commerce#673]
### Bug Description

When there are more users on the website and one of them would like to add a product to the cart, a 419 Page expired message shows up.

This happens with both the 'full' caching strategy from Statamic but also with no caching enabled at all

![Screenshot 2022-06-20 at 18 43 46](https://user-images.githubusercontent.com/1932778/174647200-b6d45ee7-a604-4ec6-9eb8-3e2233e946ca.png)
.

### Steps to reproduce

1. Add a product in the cart
2. Use a different computer or device and try to add a product to the cart
3. A 419 Page expired message shows up

### Environment

Statamic 3.3.16 Pro
Laravel 9.17.0
PHP 8.0.15
doublethreedigital/simple-commerce 3.2.9

**Comment by duncanmcclean** [comment]
You'll need to follow the documentation around [static caching](https://simple-commerce.duncanmcclean.com/kb-articles/static-caching).

It's probably happening when disabling static caching because you haven't cleared your 'static cache'

**Comment by qbixx** [comment]
When setting up the static caching function, I've excluded the cart URL like below:

```
'exclude' => [
        '/cart',
        '/checkout',
        '/checkout/information',
        '/checkout/complete',
        '/checkout/error',
        '/checkout/offsite/mollie',
    ],
```

However that doesn't seem to do the trick.

After that I've disabled the cache completely and run the `php artisan cache:clear` command. However the 419 page expired still shows up. Is there something else I need to do?

**Comment by duncanmcclean** [comment]
You'll also need to exclude product pages etc (anywhere with a Simple Commerce form). 

Also, to clear the static cache you need to run `php please static:clear`.

**Comment by qbixx** [comment]
Unfortunately, for some reason that doesn't seem to be working. I've completely disabled the cache, cleared the cache, run `php please static:clear` and to be safe restarted the server. But the 419 page expired page keeps showing up.

You can check on https://www.toos.nu/producten/cadeau-doos.

**Comment by duncanmcclean** [comment]
It's definitely still being static cached because the CSRF token is the same even if I open the page up in multiple browsers (it should be different for each user).

If the command isn't working, you can just delete all the files in the static caching path, probably `public/static`.

**Comment by qbixx** [comment]
Mmm, really strange. I removed the files manually but it still doesn't work.

I'm using the following env variables:

```
STATAMIC_STATIC_CACHING_STRATEGY=null

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
```

I can see the different sessions inside `/storage/frameworks/sessions` showing up. I can also see that the CSRF token stays the same. But I have no idea why.

**Comment by duncanmcclean** [comment]
I'm not sure why that's happening... as it's not strictly Simple Commerce related, try asking in a GitHub Discussion or on the Statamic Discord.

**Comment by qbixx** [comment]
Ok, thanks! Will do.
