### ISSUE TITLE
Mollie back to website shows the completed order page

### ISSUE THREAD

**Issue by qbixx** [damcclean/simple-commerce#674]
### Bug Description

When using the Mollie payment gateway and you click in the left bottom corner to not do a payment but go back to the website, you are being redirect to the order success page. The user sees the confirmation that the order was successful but of course it wasn't since the payment was stopped. The order however doesn't get confirmed in the back office from Statamic and no order confirmation is being send by email.

### Steps to reproduce

1. Setup the Mollie payment gateway
2. Place an order
3. On the Mollie page click on the bottom left link to go back to the website
4. The order confirmation page is shown

### Environment

Statamic 3.3.16 Pro
Laravel 9.17.0
PHP 8.0.15
doublethreedigital/simple-commerce 3.2.9

**Comment by TomDDms** [comment]
This exact issue is happening once more. When I click the back button I get redirected to the redirectUrl used to show an order confirmation

**Comment by duncanmcclean** [comment]
> This exact issue is happening once more. When I click the back button I get redirected to the redirectUrl used to show an order confirmation

This issue is a 1.5 years old - please open a new one.
