### ISSUE TITLE
Sometimes items on an order are not stored as JSON array but as JSON objects

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#676]
### Bug Description

I'm using the Simple Commerce plugin in combination with Runway.

Sometimes the product items are store in the incorrect format in the database table which results in not being able to view them in the CP. It's not clear when and why this happens, but maybe you have an idea.

Below is a screenshot of the Orders CP view in Simple Commerce for the last two orders:
![image](https://user-images.githubusercontent.com/81617758/174563626-d6f70344-b8ac-4f81-a99b-b3ab7b714e2c.png)

Following is data from the first order in the overview:

`{"0": {"id": "fedcb2b6-941c-406f-8cb5-5cbfc3e97177", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 100, "product": "24173ec0-5104-4d65-8ee5-7dbf9b4ce7f1", "variant": null, "metadata": [], "quantity": 1}, "4": {"id": "a84121ad-2ddb-4fc9-8725-d584fbc60fdc", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 200, "product": "a9f67df3-4569-41f8-b477-dfa189b15a09", "variant": null, "metadata": [], "quantity": 1}, "5": {"id": "af34916c-e422-488f-a80c-bb0121f0bc86", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 300, "product": "f3b3a75b-ea1e-4ad4-b66b-98c20a4f78bd", "variant": null, "metadata": [], "quantity": 1}, "6": {"id": "9995f893-f53f-4ba2-b79e-18aeea65aa81", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 400, "product": "a3e2db11-f34f-445b-a322-8e54231987e4", "variant": null, "metadata": [], "quantity": 1}, "7": {"id": "4d3cb65d-1263-47ab-9f8b-74c5918156d0", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 500, "product": "1e0f98ab-ba8d-402f-ba71-5e4b8d30deba", "variant": null, "metadata": [], "quantity": 1}}`

Following is data from the second order in the overview:
` [{"id": "47ad85a2-bdd4-4371-97d0-8a1435a9edab", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 100, "product": "6d301e16-fb13-4d9d-bd9a-f8ba60b99095", "variant": null, "metadata": [], "quantity": 1}, {"id": "a8d2907b-7a4e-480c-aa4f-8a28c2c73f73", "tax": {"rate": 0, "amount": 0, "price_includes_tax": false}, "total": 200, "product": "a5717e17-87a0-46e6-99d7-a20d57e5c0e8", "variant": null, "metadata": [], "quantity": 1}]`

If I change the first one to match the correct JSON array style it works as expected.

### Steps to reproduce

Not sure yet how this can be reproduced.

### Environment

```
Statamic 3.3.13 Pro
Laravel 8.83.15
PHP 8.0.8
doublethreedigital/runway 2.3.8
doublethreedigital/simple-commerce 3.2.6
joetannenbaum/antlers-stack-tags 0.1.0
optimoapps/statamic-bard-text-align 1.0.2
roorda-ict/statamic-entries-export 1.0.0
```

**Comment by duncanmcclean** [comment]
Okay, the second JSON blob you copied is how they all should be. 

Do you know how the orders were 'transformed' into the first blob you copied in - just by saving the order?

**Comment by itsmesaskovic** [comment]
This was a FE user action only.
It does seem that the user removed some products from the order. Since it
starts at 0 and skips to 4

Op ma 20 jun. 2022 19:08 schreef Duncan McClean ***@***.***>:

**Comment by duncanmcclean** [comment]
Ah - managed to reproduce it. Looks like it's a Simple Commerce problem after removing an item from the cart. 

Should be a case of adding `->values()` to wherever is setting the line items.
