### ISSUE TITLE
How to set a custom (boolean) field for a Customer

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#680]
### What's the issue you're running into?

In our shop we want to register the optin for a customer.
For this we added the `optin` column to the customers table:

```
    public function up()
    {
        Schema::table('customers', function (Blueprint $table) {
            $table->boolean('optin')->nullable()->default(false);
        });
    }
```

The column is available in the database after migrating.

Now we are setting this within the information page, the same way as the other fields:
```
{{ sc:cart:update redirect="/shop/checkout/payment" id="form" }}
....
<input class="form-check-input" type="checkbox" id="optin" name="optin" value="1">
{{ /sc:cart:update }}
```

Clicking the checkbox and going to the payment doesn't store a true value for this checkbox.

We've tried adding it to a custom CustomerModel as well but to no success:
```
...
    protected $fillable = [
        'name', 'email', 'optin'
    ];

    protected $casts = [
        'data' => 'json',
        'optin' => 'boolean',
    ];
...
```

The fields is not set and also not written in the Customer (or Order) data column:
![image](https://user-images.githubusercontent.com/81617758/175004637-e96aca73-98d9-4022-b3c0-44c14b19b974.png)

Your advice is welcome.

### Steps to reproduce

See steps describe in the table above.

### Environment

Statamic 3.3.16 Pro
Laravel 8.83.15
PHP 8.0.8
doublethreedigital/runway 2.3.8
doublethreedigital/simple-commerce 3.2.9
joetannenbaum/antlers-stack-tags 0.1.0
optimoapps/statamic-bard-text-align 1.0.2
roorda-ict/statamic-entries-export 1.0.0

**Comment by duncanmcclean** [comment]
The name of the input should be `customer[optin]` so it's saved on the customer and you'll need to add `optin` to the 'field whitelist' in your Simple Commerce config.

**Comment by itsmesaskovic** [comment]
Thank you for this info Duncan!

I made the changes accordingly and get the following error:
` (ErrorException(code: 0): Array to string conversion at /var/www/nofam-acc/vendor/doublethreedigital/simple-commerce/src/Http/Controllers/CartController.php:51)`

It seems that because of adding the customer array the code expects the customer object/array to be set, but somehow it's empty and this error is thrown.

Data being set:
```
array:16 [▼
  "_error_redirect" => "/shop/checkout/information"
  "shipping_name" => "Saša"
  "shipping_email" => "my@email.com"
  "shipping_country" => "NL"
  "name" => "Saša"
  "email" => "my@email.com"
  "shipping_address" => "Street"
  "shipping_address_line2" => "99"
  "shipping_postal_code" => "7676 XX"
  "shipping_city" => "Almelo"
  "radio_dhl_servicepoint" => "DHL"
  "dhl_servicepoint_name" => null
  "donation_amount" => null
  "donation_amount_other" => null
  "optional_donation" => "175"
  "customer" => array:1 [▼
    "optin" => "1"
  ]
]
```

Just to understand it good. The default customer fields do not need this special identification with customer[], from the sc:update form, right?

**Comment by duncanmcclean** [comment]
The `name` and `email` fields are special, they are saved to the customer. Everything else will attempt to be saved to the order. 

If you try setting the name and email with the customer array syntax instead, does that work?

```html
<input type="text" name="customer[name]">
<input type="email" name="customer[email]">
<input type="checkbox" name="customer[opin]">
```

**Comment by itsmesaskovic** [comment]
That works, thanks!

Did have to rewrite a small part for the Alpine/Iodine validation, since it uses name and not id from the input.

**Comment by duncanmcclean** [comment]
Fab! Glad you managed to get it working.

**Comment by itsmesaskovic** [comment]
Thank you for your swift support!
