### ISSUE TITLE
Coupons scoped to specific products/items

### ISSUE THREAD

**Issue by barchard** [damcclean/simple-commerce#682]
### What would you like to see added?

Couple codes should be able to be for specific products only. For instance, X% off of Product Y should not apply to the entire cart.

### Is there a workaround you can use in the meantime?

No

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
If you update your coupons blueprint to include a [`products` field](https://github.com/doublethreedigital/simple-commerce/blob/3.x/resources/blueprints/collections/coupons/coupons.yaml#L60), you can then have the coupon only apply to specific products.

For reference, here is the [default coupons blueprint file](https://github.com/doublethreedigital/simple-commerce/blob/3.x/resources/blueprints/collections/coupons/coupons.yaml).
