### ISSUE TITLE
Upgrade from v2.3.69 to 2.4.11 seem incomplete

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#685]
### Bug Description

I've recently upgraded from v2.3.69 to 2.4.11.
Missing quite some fields in the blueprints (like the hidden field for the order number). Looks like the upgrade did't update all the files. Not sure what i'm missing, but ordering is impossible at the moment. Could use some help.

### Steps to reproduce

upgrade from v2.3.69 to 2.4.11

### Environment

Statamic 3.3.16 Solo
Laravel 8.83.18
PHP 7.4.27
cnj/seotamic 2.0.6
doublethreedigital/duplicator 2.3.1
doublethreedigital/simple-commerce 2.4.11
pecotamic/sitemap 1.4.0

**Comment by studiovlijmscherp** [comment]
Extra info;  when ordering and using Mollie as a Gateway - we have  no order number.  Looks like we  do not get one  assigned.

**Comment by duncanmcclean** [comment]
Try simply replacing your order blueprint with the [default one](https://github.com/doublethreedigital/simple-commerce/blob/2.4/resources/blueprints/collections/orders/orders.yaml) in the `2.4` branch, along with adding the title formats to the [customer](https://github.com/doublethreedigital/sc-starter-kit/blob/main/content/collections/customers.yaml) & [order collections](https://github.com/doublethreedigital/sc-starter-kit/blob/main/content/collections/orders.yaml).

These parts of the upgrade process should have been automated but sometimes they just won't work 🤷 . It's not something I'm planning to fix for v2.4 as it's no longer a version [that's supported](https://simple-commerce.duncanmcclean.com/kb-articles/support-versioning#content-support-policy).

**Comment by studiovlijmscherp** [comment]
The problem  doesn't seem to be the blueprints or collection settings; the order_number  / title simply isn't set /  created / saved (?) when a new order is made. We only get a '#' as order number  / title:

<img width="703" alt="Schermafbeelding 2022-07-16 om 10 40 18" src="https://user-images.githubusercontent.com/3353713/179347622-36cebe0d-c347-4316-9303-559d4bed5b69.png">

<img width="772" alt="Schermafbeelding 2022-07-16 om 10 42 32" src="https://user-images.githubusercontent.com/3353713/179347636-8d18418a-d848-40b7-b869-2012b5845dfe.png">

**Comment by studiovlijmscherp** [comment]
Really hope you can help. My client is getting disappointed in my services :-(

**Comment by duncanmcclean** [comment]
You need to set the collection title format in the collection settings for the title to be generated.

**Comment by duncanmcclean** [comment]
Is there anything set as the `order_number` if you look at the order's file?

v2.4 isn't really supported anymore (eg. no bug fixes) but I'm happy to take a look at the site if you invite me to the Git repository.

**Comment by studiovlijmscherp** [comment]
The order_number is just  an '#'. Did some more debugging:

```site/vendor/doublethreedigital/simple-commerce/src/SimpleCommerce.php
public static function freshOrderNumber()
-- does create the correct  (next) ordernumber

site/vendor/doublethreedigital/simple-commerce/src/Orders/Order.php
public function __construct()
title: '#10001'

public function beforeSaved()
title: '#'```

i've added you to the repo. Plz do not commit anything to repo, its being auto-deployed using git-actions on commit.

**Comment by duncanmcclean** [comment]
Thanks, I'll take a look today 👍

**Comment by studiovlijmscherp** [comment]
Awesome. Thanks a lot 🙏🏻

**Comment by duncanmcclean** [comment]
Sorry, I can't seem to be able to get your site up and running... 

There's stuff missing in Git like collections, navigations etc which stop your site from functioning. I'm going to need that (it's fine if you need to strip off any customer data), either in Git or via email (help at doublethree dot digital).

**Comment by studiovlijmscherp** [comment]
Hey  Duncan,  I've just send you an email.
Thanks!

**Comment by duncanmcclean** [comment]
Just figured out how to fix it.

It turns out v2.4 doesn't use title formats at all (apologies for telling you to set them up earlier in this issue), it's only v3.x that uses them. You can remove them.

The title was being set by Simple Commerce but later overridden with details of the current site - probably due to a copy and paste mistake.

I've submitted a pull request to your project, feel free to review. As [v2.4 isn't supported anymore](https://simple-commerce.duncanmcclean.com/kb-articles/support-versioning#content-support-policy), I'm not going to tag a release that fixes this.

For anyone in the future that comes across this, apply [this diff](https://gist.github.com/duncanmcclean/153b1d90929ce261c4f5b7c0317c5db6) to your project and it should be fixed.

**Comment by studiovlijmscherp** [comment]
All seems fine. Except for the order notifications. E-mail are not being sent. E-mail config tested using the e-mail test utility (cp/utilities/email) - these  mail are sent and received.

Solved:
Not sure why, but vendor/barryvdh/laravel-dompdf/src/ServiceProvide needs a /public folder in the root. Since we're using public_html, this returned  an error. Created an empty /public folder. All  good now
