### ISSUE TITLE
TAX category not shown in CP

### ISSUE THREAD

**Issue by Kuldas** [damcclean/simple-commerce#686]
### Bug Description

Hi Duncan, 

I found a bug with the TAX category display in CP. I installed Simple Commerce as a starter kit and created a super admin account. After logging into CP, my menu does not display the category - TAX. 

### Steps to reproduce

1. Install Simple Commerce as starter kit
2. Create super admin
3. login to CP

### Environment

Statamic 3.3.20 Pro
Laravel 9.20.0
PHP 8.1.7
doublethreedigital/simple-commerce 3.2.12

**Comment by duncanmcclean** [comment]
In order to see the Tax Settings in the Control Panel, you'll need to be using the 'Standard Tax Engine', rather than the Basic one.

What's your `tax_engine` set to in your `simple-commerce.php` config file?

**Comment by Kuldas** [comment]
Hi,
Sorry, I didn't notice that I have to edit this in simple-commerce.php from `'tax_engine' => \DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine::class` to `'tax_engine' => \DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine::class`

Now it's working properly. I'll check it better next time.
