### ISSUE TITLE
Antlers tag to view prices with tax for all items in cart.

### ISSUE THREAD

**Issue by Kuldas** [damcclean/simple-commerce#687]
### What's the issue you're running into?

Is there an Antler tag in Simple Commerce so that I can display Subtotal as the prices with tax of all items in the cart? In the Czech Republic, the end customer is always shown the price with tax.
 
**For example** `{{ items_total_including_tax }}`

### Steps to reproduce

```
<tr>
    <td></td>
    <td></td>
    <td class="text-sm px-4 py-3 font-semibold">Subtotal</td>
    <td class="text-sm px-4 py-3 text-right">{{ items_total_including_tax }}</td>
</tr>
```

### Environment

Statamic 3.3.20 Pro
Laravel 9.20.0
PHP 8.1.7
doublethreedigital/simple-commerce 3.2.12

**Comment by duncanmcclean** [comment]
`{{ grand_total }}` will include taxes - does that work for you?

**Comment by Kuldas** [comment]
I can use `{{ grand_total }}` , but it creates one problem. 

If I use `{{ grand_total }}` on the subtotal in the cart and continue further in the process to select shipping, I have to complete the order. If I don't, the subtotal will return the full price with shipping when I return it to the cart.

On the cart page, I only need to return the value of the items in the cart with tax in the subtotal.

**Comment by duncanmcclean** [comment]
Gotcha - that makes sense! 

I've added a new `{{ sc:cart:itemsTotalWithTax }}` tag which will hopefully do what you want, it'll be included in the next release.
