### ISSUE TITLE
notifications not sent to customer

### ISSUE THREAD

**Issue by mmorkt** [damcclean/simple-commerce#695]
### What's the issue you're running into?

Hi, 
I'm trying to recreate a project with Simple Commerce for testing. But I can't get the notifications sent to customers.
Done some custom emails and changed the config/simple-commerce.php to:
```
   'notifications' => [
        'order_paid' => [
            \App\Notifications\CustomerOrderPaid::class => [
                'to' => 'mmorkt@example.com',
            ],
            \App\Notifications\CustomerOrder::class => [
                'to' => 'customer',
            ],
        ],
    ],
```

The static mail address works fine but the dynamic doesn't goes through.

### Steps to reproduce

Not sure...

### Environment

Statamic 3.3.17 Solo
Laravel 8.83.18
PHP 7.4.30
doublethreedigital/simple-commerce 2.4.11

**Comment by duncanmcclean** [comment]
Hello 👋 

Are your emails setup to send correctly? Can you check your email settings by going to 'Utilities -> Email', then send a test email, do you get it?

What gateway are you using?

What do those custom notification classes look like?

**Comment by mmorkt** [comment]
Yup, the test email goes through, and the static as well.

This works:
```
'notifications' => [
        'order_paid' => [
            \App\Notifications\CustomerOrderPaid::class => [
                'to' => 'mmorkt@example.com',
            ],
        ],
    ],
```

But this doesn't
```
'notifications' => [
        'order_paid' => [
            \App\Notifications\CustomerOrderPaid::class => [
                'to' => 'customer',
            ],
        ],
    ],
```


The custom notification emails are the same as https://github.com/doublethreedigital/simple-commerce/blob/2.3/src/Notifications/CustomerOrderPaid.php#L15 but changed subject and some lines in the end

**Comment by duncanmcclean** [comment]
Okay - do you have a `customer` set on the orders? It should be an ID to a customer entry/user.

**Comment by mmorkt** [comment]
Ahh then it properly works. I'm not using Customer handling. 
Is there a way to sent the email to a field of "emails" on the order?

**Comment by duncanmcclean** [comment]
Ah okay, that's why it won't be working.

If you have an email in a field you want to send to, set it to `{{ email_field }}`. You can't send it to multiple addresses though (without replicating the configuration for each email field).

**Comment by mmorkt** [comment]
Thank you Duncan.

Okay, can't refer to the field {{ emails }} in the config file. Are you referring to another file?
 
```
'notifications' => [
        'order_paid' => [
            \App\Notifications\CustomerOrderPaid::class => [
                'to' => '{{ emails }}',
            ],
        ],
    ],
```

**Comment by duncanmcclean** [comment]
You can't send to multiple addresses, I'm afraid. `to` only accepts a single email address.

**Comment by mmorkt** [comment]
it's just bad naming I'm afraid. {{ emails }} is just a single email.

**Comment by duncanmcclean** [comment]
Ah okay, that should work fine then. Still not seeing it being sent through?

**Comment by duncanmcclean** [comment]
Oh... just saw you're using an old version of SC, which only supports sending emails to fixed addresses or `customer`s. v3 supports the Antlers syntax. Sorry!

**Comment by sbrow** [comment]
Does simple commerce allow you to send these emails to multiple people? If so how would we do that?

Would something like this work?
```php
\DuncanMcClean\SimpleCommerce\Notifications\BackOfficeOrderPaid::class => [
    // Output a comma separated list, e.g. 'admin@admin.com,super@admin.com'
    'to' => '{{ users super:is="true" }}{{email}}{{ if next }},{{/if}}{{/users}}',
],

**Comment by duncanmcclean** [comment]
No, it doesn't. You can only send to a single email address. It's a good [feature request](https://github.com/duncanmcclean/simple-commerce/discussions/new/choose) though!
