### ISSUE TITLE
Customers not working as Users (in a database)

### ISSUE THREAD

**Issue by netnakgraham** [damcclean/simple-commerce#702]
### What's the issue you're running into?

After setting up and editing the config to use users as customers I have noticed that the users blueprint is not changed, and the customers nav item in the CP is a 404 (pointing at /cp/collections/users)

Also, the overview nav item results in a 500:

Call to undefined method App\Models\User::isSuper()
`28 $showEntriesWarning = $request->user()->isSuper()`

### Steps to reproduce

Have users in an sqlite database
Installed the SC package, then set the config to:

```

 'customers' => [
            'repository' => \DoubleThreeDigital\SimpleCommerce\Customers\UserCustomerRepository::class,
            'collection' => 'users',
        ],
```

run sc:install 

### Environment

PHP 8.1.6
Laravel 9.27.0
Statamic pro 3.3.32

**Comment by duncanmcclean** [comment]
No changes will be made to the user's blueprint. 

You certainly shouldn't be getting any of those errors - I'll take a look when I get a chance.

**Comment by netnakgraham** [comment]
Thanks. 
I see, do I need to add orders to my blueprint so the customer can see their orders?

**Comment by duncanmcclean** [comment]
You can do that if you want (it's optional)....

Add an 'Entries' field to your user blueprint, then add a JSON column for it in your database. SC will add to it for you when an order goes through.

**Comment by duncanmcclean** [comment]
^ The issues you pointed out in this issue should be resolved in the latest release.

**Comment by netnakgraham** [comment]
Thank you,  the customers nav is now loading users.
