### ISSUE TITLE
Email history log

### ISSUE THREAD

**Issue by barchard** [damcclean/simple-commerce#709]
### What would you like to see added?

An Email history of items sent to a Customer. This will help troubleshoot issues to know what communications have been sent to a customer (and potentially resend one if needed)

### Is there a workaround you can use in the meantime?

No

### Priority wise - where's this feature for you?

Nice to have

**Comment by duncanmcclean** [comment]
Thanks for this - moving to GitHub Discussions - but have added to the roadmap!
