### ISSUE TITLE
Variant not showing in order

### ISSUE THREAD

**Issue by rolinbos** [damcclean/simple-commerce#727]
### Bug Description

The variant field is empty when there is a variant on order.
<img width="868" alt="Screenshot 2022-10-01 at 19 06 37" src="https://user-images.githubusercontent.com/34242298/193420364-bb212a84-40be-4434-8858-f51ae0bb621c.png">

### Steps to reproduce

1. Create a Simple Commerce site
2. Add a variant as product
3. Order the variant

### Environment

Environment
Application Name: Statamic
Laravel Version: 9.33.0
PHP Version: 8.1.8
Composer Version: 2.2.3
Environment: local
Debug Mode: ENABLED
URL: simplecommerce.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.41 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.0.2

**Comment by duncanmcclean** [comment]
Thanks for reporting - this issue should be fixed now! 🚀
