### ISSUE TITLE
Update SC4 / Laravel 9: Error when using ProductType::VARIANT()

### ISSUE THREAD

**Issue by remiduval** [damcclean/simple-commerce#731]
### Bug Description

After updating to Laravel 9 & SC4, I'm getting an error on my export functionality: https://flareapp.io/share/q5YQ3Ow5#F84

For reference, the whole function is here: https://github.com/remiduval/apc/blob/2ac6746a74e218505bb890ff00645ba13892e782/app/Exports/SalesExport.php#L75

### Steps to reproduce

Using ProductType::VARIANT() on a Laravel 9/SC4 install. It used to work on Laravel 8/SC3

### Environment

Environment
Application Name: Association des Parents du CFBL
Laravel Version: 9.34.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: apc.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendinblue
Queue: sync
Session: file

Simple Commerce
Gateways: Stripe
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 8
Antlers: regex
Version: 3.3.43 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.17
aryehraber/statamic-logbook: 2.1.0
doublethreedigital/duplicator: 2.3.2
doublethreedigital/guest-entries: 1.2.2
doublethreedigital/simple-commerce: 4.0.3
optimoapps/statamic-bard-text-align: 1.0.2
rias/statamic-redirect: 2.4.0
xndbogdan/statamic-bard-text-color: 2.4.1

**Comment by duncanmcclean** [comment]
If you change it from `ProductType::VARIANT()` to `ProductType::Variant`, that should fix it.

**Comment by remiduval** [comment]
It worked, thank you so much!
