### ISSUE TITLE
When deleting a product in cart error

### ISSUE THREAD

**Issue by freshface** [damcclean/simple-commerce#732]
### Bug Description

Flare: https://flareapp.io/share/4m4LxWZm

### Steps to reproduce

1. Add a product
2. Add it to cart
3. Delete product in CP

### Environment

Environment
Application Name: Statamic Peak
Laravel Version: 9.34.0
PHP Version: 8.1.5
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.43 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.0.3

**Comment by duncanmcclean** [comment]
I'll take a look at this tomorrow, we may be able to handle deleted products better (like removing from the cart, instead of throwing an error).

In the meantime, you can clear your cookies for the site, then you'll get assigned a new cart.
