### ISSUE TITLE
Coupons not working when using EloquentCustomerRepository and runway

### ISSUE THREAD

**Issue by jornwildenbeest** [damcclean/simple-commerce#742]
### Bug Description

Error when creating coupons.

I am using simple commerce v4 and storing customers and orders in a database.
Because of that I've set up the following config in simple-commerce.php for the customers:
```
'content' => [
        'customers' => [
            'repository' => \DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository::class,
            'model' => \App\Models\Customer::class,
        ],
    ],
```

Because I am using the EloquentCustomerRepository, I get the following error when I try to create a coupon:

```
DoubleThreeDigital\Runway\Runway::findResource(): Argument #1 ($resourceHandle) must be of type string, null given, called in /Users/jorn/Sites/sc-playground/vendor/doublethreedigital/runway/src/Fieldtypes/BaseFieldtype.php on line 226
```

I did some digging in the code and the only fix I can find for now is by adding the customer resource option in the Coupons blueprint:

in the /vendor/doublethreedigital/simple-commerce/src/Coupons/CouponBlueprint.php file line 37:
change this:
```
if (self::isOrExtendsClass(SimpleCommerce::customerDriver()['repository'], EloquentCustomerRepository::class)) {
            $customerField = [
                'type' => 'has_many',
                'instructions' => 'If selected, this coupon will only be valid for selected customers.',
                'display' => 'Customers',
                'width' => 50,
            ];
        }
```

To this:

```
if (self::isOrExtendsClass(SimpleCommerce::customerDriver()['repository'], EloquentCustomerRepository::class)) {
            $customerField = [
                'type' => 'has_many',
                'instructions' => 'If selected, this coupon will only be valid for selected customers.',
                'display' => 'Customers',
                'width' => 50,
                'resource' => 'customers'
            ];
        }
```

Not sure if this is the right way to fix the issue, if it is I'm happy to setup an PR

### Steps to reproduce

1. Fresh install with sc-starter-kit: `statamic new artisan-bakery duncanmcclean/sc-starter-kit`
2. use switch to db command: `php please sc:switch-to-database`
3. Set up db etc... to get everything working
4. make sure the EloquentCustomerRepository is used in config/simple-commerce.php:

```
'customers' => [
            'repository' => \DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository::class,
            'model' => \DoubleThreeDigital\SimpleCommerce\Customers\CustomerModel::class,
        ],
```
5. Try to create an Coupon. You will see the following error:
```
DoubleThreeDigital\Runway\Runway::findResource(): Argument #1 ($resourceHandle) must be of type string, null given, called in /Users/jorn/Sites/sc-playground/vendor/doublethreedigital/runway/src/Fieldtypes/BaseFieldtype.php on line 226
```

### Environment

```
Environment
Application Name: ***
Laravel Version: 9.35.1
PHP Version: 8.1.6
Composer Version: 2.3.7
Environment: local
Debug Mode: ENABLED
URL: vitamins4life.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 3
Antlers: regex
Version: 3.3.43 PRO

Statamic Addons
aryehraber/statamic-uuid: 2.1.0
doublethreedigital/runway: 2.5.3
doublethreedigital/simple-commerce: 4.1.1
```

**Comment by jornwildenbeest** [comment]
The coupon field in the cp is not working either btw.

![image](https://user-images.githubusercontent.com/25662412/196914909-75e08dd8-f638-4b4b-80db-98f1879a0d7f.png)

haven't found a fix for that.

**Comment by duncanmcclean** [comment]
Thanks - I'll take a look at this (& your other issue) over the weekend!

**Comment by duncanmcclean** [comment]
> Not sure if this is the right way to fix the issue, if it is I'm happy to setup an PR

Yes, that'll work. Feel free to open a PR 😄 

> The coupon field in the cp is not working either btw.

We're using Statamic's Relationship fieldtype for that Coupon field which just shows as blank when it's marked as read-only (not _really_ a SC issue). When there actually is a coupon selected, it will show the coupon as expected.

**Comment by jornwildenbeest** [comment]
Great!

PR: https://github.com/duncanmcclean/simple-commerce/pull/745
