### ISSUE TITLE
Cannot use Order LineItem as array in Customer Order Shipped email

### ISSUE THREAD

**Issue by kevinmeijer97** [damcclean/simple-commerce#743]
### Bug Description

The Customer Order Shipped email generates the following error:
Cannot use object of type DoubleThreeDigital\\SimpleCommerce\\Orders\\LineItem as array.
In vendor/doublethreedigital/simple-commerce/resources/views/emails/customer_order_shipped.blade.php the $lineItem is being used as an array but it is a DoubleThreeDigital\SimpleCommerce\Orders\LineItem.

In the other email templates it is being treated as an object, but in this template as an array resulting in this error.

### Steps to reproduce

1. Create an order with a product
2. Send the order shipped email

### Environment

Below is my local device, but same error occurs on the testing and production environments.

Environment
Application Name: CityAppTour
Laravel Version: 9.35.1
PHP Version: 8.1.9
Composer Version: 2.3.10
Environment: local
Debug Mode: ENABLED
URL: cityapptour.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Dummy, Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 7
Antlers: regex
Version: 3.3.44 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.1.0
edalzell/blade-directives: 3.7
mitydigital/iconamic: 1.0.6
simonridley/tracking-code-manager: dev-master
spatie/statamic-responsive-images: 2.14.0
webographen/statamic-dynamic-token: 1.0.0
withcandour/aardvark-seo: 2.0.28

**Comment by duncanmcclean** [comment]
Good catch - not sure why that email code wasn't changed when I changed the others 😅 . Fix incoming.
