### ISSUE TITLE
Error Undefined array key "data" with Paypal gateway

### ISSUE THREAD

**Issue by el-schneider** [damcclean/simple-commerce#755]
### Description

I'm getting this exception when setting up Paypal gateway with `offsite` mode and trying a payment in sandbox mode.

Here is the shared exception: https://flareapp.io/share/67OKLOJ7#F60

### Steps to reproduce

1. Create new project with starter-kit 
2. Set-up Paypal as a gateway with `'mode' => 'offsite'`
3. Finish payment through sandbox account 

### Environment

Environment
Application Name: Statamic
Laravel Version: 9.35.1
PHP Version: 8.1.11
Composer Version: 2.4.3
Environment: local
Debug Mode: ENABLED
URL: statamic-simple-commerce-starter-kit.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: PayPal
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: regex
Version: 3.3.44 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.0.3

**Comment by duncanmcclean** [comment]
This is an issue with Simple Commerce itself - moving to the Simple Commerce repository. I'll review when I have some time.
