### ISSUE TITLE
Customer is empty in order detail

### ISSUE THREAD

**Issue by adriaanglibert** [damcclean/simple-commerce#763]
### Description

Customer appears empty on the detail of an order. 

If you look at a successful order in the CP the customer that the order is linked to looks weird (see screenshot). If I look at the order .md file there is a customer id on it that is the correct customer id.

<img width="409" alt="Screenshot 2022-12-07 at 13 32 32" src="https://user-images.githubusercontent.com/74193342/206180230-53ae0e3d-9ea0-409e-b31f-dba1b38e83d1.png">

The main issue is the title field being empty when creating customers.

<img width="868" alt="Screenshot 2022-12-07 at 13 33 08" src="https://user-images.githubusercontent.com/74193342/206180349-90891017-d596-471d-b2cd-f07cd91f6598.png">

I did set my whitelist and used the coded from the starter as a guide.

```
    'field_whitelist' => [
        'orders' => [
            'shipping_name', 'shipping_address', 'shipping_address_line1', 'shipping_address_line2', 'shipping_city',
            'shipping_region', 'shipping_postal_code', 'shipping_country', 'shipping_note', 'shipping_method',
            'use_shipping_address_for_billing', 'billing_name', 'billing_address', 'billing_address_line2',
            'billing_city', 'billing_region', 'billing_postal_code', 'billing_country',
        ],

        'line_items' => [],

        'customers' => ['name', 'email'],
    ],
```

Any idea what could be causing this?

### Steps to reproduce

1. Place an order in the front-end using the started code
2. Look at an order

### Environment

```
Environment
Application Name: Statamic
Laravel Version: 9.43.0
PHP Version: 8.1.10
Composer Version: 2.4.2
Environment: local
Debug Mode: ENABLED
URL: your-new-site-name.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: regex
Version: 3.3.60 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.0.3
```

**Comment by duncanmcclean** [comment]
If you go & edit the Customers collection, what is the 'title format' set to? 

Is this a new site or have you updated from a previous version?

Have you changed anything in the customer blueprint?

**Comment by adriaanglibert** [comment]
Thanks for the quick reply! It was a site created a couple of months ago using the starter of Simple Commerce.
The title format was empty in the backend even though `title_format: '{name} <{email}>'` was set in the `.md` (which is why I didn't check it)

It now works after setting the Title format!

**Comment by duncanmcclean** [comment]
That's weird - the title format should have been set properly when updating. It's possible something was cached. 

I'll close this issue now.
