### ISSUE TITLE
Get a single gateway not working

### ISSUE THREAD

**Issue by WasMachenSachen** [damcclean/simple-commerce#774]
### Description

I'm trying to [access a single gateway](https://simple-commerce.duncanmcclean.com/tags/gateways#content-get-a-gateway) which isn't working.

I think the problem is the [underlying function](https://github.com/duncanmcclean/simple-commerce/blob/b3bca07ca8239a9cebb2133c5ac2923b450fc45d/src/Tags/GatewayTags.php#L23
): 
```php
 public function wildcard(string $tag)
    {
        return collect(SimpleCommerce::gateways())
            ->where('handle', $this->params->get('handle'))
            ->first();
    }
```
`->where` should first receive the key and then the value, see [here](https://laravel.com/docs/9.x/collections#method-where).

I tinkered a little and this seems to fix the problem:
```php
    public function wildcard(string $tag)
    {
        return collect(SimpleCommerce::gateways())
            ->where('handle', $tag)
            ->first();
    }
```

### Steps to reproduce

use the provided example
```html
{{ sc:gateways:stripe }}
    <h2>Payment with {{ display }}</h2>
    <!-- Whatever else you need to do -->
{{ /sc:gateways:stripe }}
```

### Environment

Environment
Application Name: Statamic
Laravel Version: 9.41.0
PHP Version: 8.2.0
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: URL.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Dummy, Stripe, PayPal, Klarna
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Versand
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: regex
Version: 3.3.58 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.2.4

**Comment by duncanmcclean** [comment]
Thanks for letting me know - I've copied over your fix & written a test to verify it's fixed. I'll push out a release shortly.
