### ISSUE TITLE
Items (JSON) data is corrupted upon manual update

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#789]
### Description

In the CP when we change an (DB) order (e.g. cp/runway/orders/10952) our items (JSON) data gets corrupted.

The first customer order is untouched. The second has been flagged as shipped.

![image](https://user-images.githubusercontent.com/81617758/213701228-497e1fbe-afdd-4797-aa55-1e0e2066c29b.png)

### Steps to reproduce

1. Open a paid customer order
2. Change a field
3. Results in corrupt data set (items)

### Environment

Environment
Laravel Version: 9.47.0
PHP Version: 8.1.11    
Composer Version: 2.4.2

Drivers
Broadcasting: log      
Cache: statamic        
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Letterbox shipping method, Package shipping method
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 7
Antlers: regex
Stache Watcher: Enabled
Static Caching: half
Version: 3.3.64 PRO

Statamic Addons
doublethreedigital/runway: 2.6.3
doublethreedigital/simple-commerce: 4.4.0
joetannenbaum/antlers-stack-tags: 0.1.0
mitydigital/sitemapamic: 2.3.5
optimoapps/statamic-bard-text-align: 1.0.2
roorda-ict/statamic-entries-export: 1.0.1
stoffelio/statamic-turnstile: 1.0

**Comment by duncanmcclean** [comment]
Thanks for reporting this!

I've tagged a release in Runway which should fix this issue for you ([v2.6.4](https://github.com/duncanmcclean/runway/releases/tag/v2.6.4)).
