### ISSUE TITLE
Products' price fields behave weird

### ISSUE THREAD

**Issue by studiovlijmscherp** [damcclean/simple-commerce#791]
### Description

When updating of changing prices for a product (Regular product or Product variants) the numbers in the price field jump around and are (most of the time) not saved correct.

I have recorded the issue here:
https://www.loom.com/share/2c020a7604a34cce8559fce326f26d3f

### Steps to reproduce

- Update a price
- Watch the numbers jump around

### Environment

Environment
Application Name: BeefsAndBeers
Laravel Version: 9.45.1
PHP Version: 8.2.0
Composer Version: -
Environment: local
Debug Mode: ENABLED
URL: beefsandbeers.wip
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp_mailtrap
Queue: sync
Session: file

Simple Commerce
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Gratis afhalen in Hellendoorn, Bezorging binnen Twente, Bezorging buiten Twente (alleen zaterdagen in oneven weken)
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 4
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 Solo

Statamic Addons
cnj/seotamic: 2.1.0
doublethreedigital/duplicator: 2.3.4
doublethreedigital/simple-commerce: 4.4.2
pecotamic/sitemap: 1.4.0

**Comment by duncanmcclean** [comment]
I'm really sorry, I can't reproduce this locally. The input works as expected, just like a text input: https://www.loom.com/share/a8ceadd137b1483eb7d450423615b5fd

I've tried changing my currency from GBP to EUR in case that changes anything. I've also tried editing the price from different parts (just after the `.`, at the start/end) and I couldn't see anything out of the ordinary.

Can you reproduce the same issue in a fresh site using the [starter kit](https://simple-commerce.duncanmcclean.com/installation#content-installing-with-the-starter-kit)?

**Comment by duncanmcclean** [comment]
Nevermind, I can reproduce it on a different site.

**Comment by duncanmcclean** [comment]
I've just tagged a release which hopefully contains a fix to this issue. 😅 

Let me know if it doesn't and I can re-open.
