### ISSUE TITLE
Stock checking not working when updating through Ajax

### ISSUE THREAD

**Issue by el-schneider** [damcclean/simple-commerce#797]
### Description

When I' updating a products quantity through `/!/simple-commerce/cart-items/${id}`, the updated quantity doesn't seem to be checked against the stock.

### Steps to reproduce

perform an update against `/!/simple-commerce/cart-items/${id}` with a quantity, that is higher than the stock

### Environment

Environment
Application Name: N&MS
Laravel Version: 9.48.0
PHP Version: 8.1.14
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: nandms.statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: PayPal
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.0 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.5.1

**Comment by duncanmcclean** [comment]
A couple of questions:

* Does the product have variants?
* Do you have a field with the handle of `stock` on your Product blueprint
* What is the stock set to on the product?
* What is the quantity you're trying to add to the product?

**Comment by el-schneider** [comment]
- no
- yes
- 1
- I'm trying to update to quantity 2

It works fine, when adding it, if it hasn't been in the card before and if I'm using `/!/simple-commerce/cart-items`.

**Comment by duncanmcclean** [comment]
Ah okay, it's updating that's the issue? Cool, I'll try and get that fixed in the next few days.

**Comment by el-schneider** [comment]
I realized now that it might not be necessary for me after all, if this: https://github.com/duncanmcclean/simple-commerce/discussions/798 would be possible

**Comment by duncanmcclean** [comment]
> I realized now that it might not be necessary for me after all, if this: #798 would be possible

Simple Commerce should 100% be checking the stock when you update the quantity of a product in the cart. You shouldn't need to worry about checking that yourself.
