### ISSUE TITLE
Mollie Payment does not hit webhook?

### ISSUE THREAD

**Issue by wneid** [damcclean/simple-commerce#890]
### Description

Hi, i am trying to integrate Simple Commerce with mollie Payments but the payment only set to paid in mollie and not in simple commerce.
I found this in my ngrok overview:
`POST /!/simple-commerce/gateways/mollie/webhook HTTP/1.1`

`500 Internal Server Error`
`The connection was closed before this response could be fully read; 0 bytes were captured. The error encountered while reading the response body was "unexpected EOF".`

In the Laravel log there is this Error Message:
`[2023-07-20 08:20:31] local.ERROR: Undefined variable $mollieId {"exception":"[object] (ErrorException(code: 0): Undefined variable $mollieId at /var/project/src/vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/MollieGateway.php:158)`

I added an var_dump($errorMessage); followed by an die(); in the withErrors Function in the BaseActionController.php
When i get redirected by mollie to my website i get this message:
`Order [#1201] has not been marked as paid yet.`

Setup was made according to Documentation, do you have any idea how to fix this?

### Steps to reproduce

1. Inserted Mollie API Test Key and Profile ID into .env file
2. Added Mollie Gateway Code from Documentation into simple-commerce.php file
3. Created Cart, Checkout, Thanks and Error Sites
4. Started ngrok & changed APP_URL in .env file to ngrok URL
5. Tested Payment:
- I added Product X to my cart
- Then i clicked on a link to my checkout Page and get redirected to mollie
- I select an Payment Method, set the status of Payment on "paid" and press on continue
- Now i get Redirected to my error_redirect URL

### Environment

Environment
Laravel Version: 10.15.0
PHP Version: 8.1.17
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 8
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
doublethreedigital/simple-commerce: 5.3.0
ncla/statamic-focal-point-fieldtype: 3.0.0
rias/statamic-color-swatches: 2.2.0
stillat/meerkat: 3.0.0
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 4.0.1
studio1902/statamic-peak-tools: 3.2

**Comment by duncanmcclean** [comment]
I think this is a bug in Simple Commerce itself - I'll fix it tonight.
