### ISSUE TITLE
Order Date Not Populated

### ISSUE THREAD

**Issue by jamie-b5** [damcclean/simple-commerce#931]
### Description

Hi Duncan

Our client (reasonably!) wants to see the order date on their Orders index.

The field Paid At (paid_date) is not populated, despite the order being placed and paid. I was able to display the array Status Log but ideally we want to show the paid date or placed date from this array separately. See the screenshot below.

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/a0d8e0fb-9504-4909-b19c-91d3c3277ba6)

My user yaml looks as follows (just in relation to the orders preferences):

orders:
      per_page: 100
      columns:
        - title
        - status_log
        - customer
        - grand_total
        - paid_date
        - tracking_ref
        - items_total
        - 
I have tried to isolate the paid element of the Status Log array with no joy. I have tried - status_log.paid -status_log [paid] and various other attempts guided by this page https://www.w3schools.io/file/yaml-arrays/

Can you either advise me what I need to do to get the paid or placed date showing from this array, or alternately how to get the paid_date field to be populated once the order has successfully gone through the payment phase?

This has also been raised in discussions by another user https://github.com/duncanmcclean/simple-commerce/discussions/896

Thanks as always!

### Steps to reproduce

- go to Admin Orders Index
- Customise Columns
- Add in Status Log

Appears as an array when we only want the nested paid or placed date.

Alternately we would like the paid_date field to be updated when the customer pays. At the moment this is empty on completed orders.

### Environment

Environment
Application Name: Sound Organisation
Laravel Version: 10.22.0
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: sound_org.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Stripe
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Overnight Shipping, Click and Collect
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
doublethreedigital/simple-commerce: 5.6.0
jezzdk/statamic-google-maps: 1.2.2
rias/statamic-data-import: 1.3.0

**Comment by duncanmcclean** [comment]
Unfortunately, this is not currently possible but is something I'm planning on adding at some point. There's a feature request you can upvote here: #896

In the meantime, you can create a [computed field](https://statamic.dev/computed-values#overview) to display it instead.
