### ISSUE TITLE
Cannot change status of an order to 'dispatched' as admin

### ISSUE THREAD

**Issue by simonfrost** [damcclean/simple-commerce#933]
### Description

We have a successfully Placed and Paid order, but cannot see how to move this to an order status of Dispatched (Shipped). The fields are read only by default. Thanks.

![Screenshot 2023-11-09 at 16 31 51](https://github.com/duncanmcclean/simple-commerce/assets/125280/f255fdec-7a31-47f8-b10e-ebab26c43377)

### Steps to reproduce

Customer orders an item.
Successfully pays.
Admin logs in to process order.
Cannot change order status.

### Environment

Environment
Application Name: Sound Organisation
Laravel Version: 10.22.0
PHP Version: 8.1.21
Composer Version: 2.4.2
Environment: production
Debug Mode: OFF
URL: soundorg.co.uk
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Stripe
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Overnight Shipping, Click and Collect
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.21.0 PRO

Statamic Addons
doublethreedigital/simple-commerce: 5.6.0
jezzdk/statamic-google-maps: 1.2.2
rias/statamic-data-import: 1.3.0

**Comment by duncanmcclean** [comment]
You can't change the order / payment status in the publish form. 

They can only be changed by either checking out (for the Paid & Placed statuses) or via an action on the Orders Listing Table. 

After statamic/cms#6375 is merged, you'll also be able to change the statuses on the orders show page (the page with the publish form).

**Comment by simonfrost** [comment]
Understood. Look forward to the merge/update.
