### ISSUE TITLE
Site config not found [deutsch]

### ISSUE THREAD

**Issue by j3ll3yfi5h** [damcclean/simple-commerce#935]
### Description

Hello @duncanmcclean 
I'm currently trying out your simple commerce addon and installed it inside an existing installation. I only have one site, but the site handle was changed from `default` to `deutsch`.

Because of this it's returning an error:
`Site config not found [deutsch]`

### Steps to reproduce

1. Install Statamic (no multisite)
2. Change site handle from `default` to something else
3. Install SC with composer
5. Login and try to create a product
6. See the error.

### Environment

Laravel Version: 10.32.1
PHP Version: 8.2.11
Statamic: 4.34.0 PRO
doublethreedigital/simple-commerce: 5.6.0

**Comment by duncanmcclean** [comment]
What do these two files look like?

* `config/statamic/sites.php`
* `config/simple-commerce.php`

For each of the sites you have setup in `sites.php`, you need to [configure them](https://simple-commerce.duncanmcclean.com/guides/multisite#guides/multisite) in your `simple-commerce` config.

**Comment by j3ll3yfi5h** [comment]
Aha! Alright...not a bug then. 😅 Thank you for the clarification!
