### ISSUE TITLE
Status Log field CP Routes not working

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#958]
### Description

On opening a order page inside the CP. I get the following error: 
`Route [statamic.cp.simple-commerce.fieldtype-api.status-log] not defined.`
Probably due to the changes in #956. 

The CP route is customized to /admin instead of /cp inside the cp.php config (maybe that causes the issue?) and it is using runway for the orders collection. 

### Steps to reproduce

1. Open order page using database orders and different cp route prefix
2. Error occurs

### Environment

Environment
Application Name: XXXX
Laravel Version: 10.39.0
PHP Version: 8.1.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR, EUR, EUR, EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: MTC Pallet Zending, PostNL International
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.0 PRO

Statamic Addons
aerni/advanced-seo: 2.4.0
appswithlove/statamic-one-click-content-translation: 4.35.0
aryehraber/statamic-impersonator: 2.6.0
aryehraber/statamic-logbook: 3.1.0
doublethreedigital/runway: 5.6.0
doublethreedigital/simple-commerce: 5.8.0
heidkaemper/statamic-toolbar: 1.1.1
rias/statamic-data-import: 1.3.0
statamic/collaboration: 0.7.3

**Comment by duncanmcclean** [comment]
Your routes are cached. Running `php artisan route:clear` should fix the issue.
