### ISSUE TITLE
Status Log Fieldtype returning 422 Unprocessable Content (empty body) 

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#966]
### Description

The request to `/admin/simple-commerce/fieldtype-api/status-log` has failed because the payload was completely empty. So when opening the Status Log panel this request gets 422 error. I'm using Database orders via Runway. 

Therefore this is the response:
```
{
    "message": "The given data was invalid.",
    "errors": {
        "order_id": [
            "This field is required."
        ]
    }
}
```
Any idea why that happens?

Some screenshots of the request to the fieldtype-api: 

<img width="510" alt="2024-01-13 om 11 39 04" src="https://github.com/duncanmcclean/simple-commerce/assets/129582223/b50cdbcf-4ac3-4340-a04c-61af8fdf98db">
<img width="511" alt="2024-01-13 om 11 39 08" src="https://github.com/duncanmcclean/simple-commerce/assets/129582223/3e8e043b-8805-45a0-beb8-2071c8a2a3d3">
<img width="509" alt="2024-01-13 om 11 39 13" src="https://github.com/duncanmcclean/simple-commerce/assets/129582223/c860a86c-8201-4984-aeae-bae31825d435">

### Steps to reproduce

1. Have database orders via Runway enabled
2. Open Status Log field inside a order 
3. Check request to Fieldtype api

### Environment

Environment
Application Name: XXXX
Laravel Version: 10.40.0
PHP Version: 8.1.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR, EUR, EUR, EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Pallet, PostNL International
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
aerni/advanced-seo: 2.4.0
appswithlove/statamic-one-click-content-translation: 4.35.0
doublethreedigital/runway: 5.6.1
doublethreedigital/simple-commerce: 5.9.1
heidkaemper/statamic-toolbar: 1.1.1
statamic/collaboration: 0.7.3

**Comment by duncanmcclean** [comment]
This should be fixed after updating Runway to [v5.6.2](https://github.com/statamic-rad-pack/runway/releases/tag/v5.6.2).
