### ISSUE TITLE
Dashboard widgets report wrong data while using Eloquent

### ISSUE THREAD

**Issue by sdussaut** [damcclean/simple-commerce#980]
### Description

Hi!

I am using Simple Commerce with the Eloquent driver (sqlite database) for the orders and customers.

It seems there is something wrong with the widgets as:

- the Number of Orders widget always report 0 orders (while I have some)
- the Recent Orders widgets returns the 5 oldest orders and not newest ones
- Top Customers are fine

Thanks!

### Steps to reproduce

1. Have the orders stored in an sqlite DB
2. Make an order
3. It should appear on the top widget

![dashboard-widgets](https://github.com/duncanmcclean/simple-commerce/assets/643853/b2431152-427f-45b3-aa9f-ef966f099e8b)

### Environment

Environment
Application Name: Test site
Laravel Version: 10.40.0
PHP Version: 8.3.1
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: test-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
doublethreedigital/sc-digital-products: 5.1.2
doublethreedigital/simple-commerce: 5.9.2
statamic-rad-pack/runway: 5.6.2

**Comment by duncanmcclean** [comment]
Hey 👋

I'm primarily working on Simple Commerce v6, which removes the Overview page and makes these "widgets" available as Control Panel Dashboard widgets instead. It also makes some improvements to how these queries are done behind the scenes.

This probably won't get fixed for v5 but for v6 instead.

**Comment by sdussaut** [comment]
Hi! Thanks for your answer!

I understand the focus on the next version. I'll see if I try to fix them on my own for now or simply just wait for v6.
Aside question, do you happen to have a roadmap for the v6 version published?

**Comment by duncanmcclean** [comment]
No, the roadmap isn't public. 

There's nothing too exciting in v6 - apart from the removal of the Overview page, reducing technical debt and introducing some necessary breaking changes.

The Digital Products addon *may* also be merged into the main Simple Commerce package too but I haven't made my mind up yet.
